'\"macro stdmacro
.\"
.\" Copyright (c) 2014 Red Hat.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMDADMCACHE 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdadmcache\f1 \- Device Mapper Cache PMDA
.SH DESCRIPTION
\f3pmdadmcache\f1 is a Performance Metrics Domain Agent (PMDA) which exports 
metric values about device mapper cache target devices, made available by the
.B dm-cache
Linux kernel module.
.PP
The device mapper cache target aims to improve the performance of a block
device (such as a spindle) by dynamically migrating some of its data to a
faster, smaller device (such as a Solid State Drive).
.PP
This PMDA exports metrics for each configured cache, including sizes,
cache read and write hits and misses, rates of cached block demotion
and promotion, and the mode each cache is operating in.
.SH INSTALLATION
Install the dmcache PMDA by using the Install script as root:
.PP
      # cd $PCP_PMDAS_DIR/dmcache
.br
      # ./Install
.PP
To uninstall, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/dmcache
.br
      # ./Remove
.PP
\fBpmdadmcache\fR is launched by \fIpmcd\fR(1) and should never be executed 
directly. The Install and Remove scripts notify \fIpmcd\fR(1) when the 
agent is installed or removed.
.SH FILES
.IP "\fB$PCP_PMDAS_DIR/dmcache/Install\fR" 4 
installation script for the \fBpmdadmcache\fR agent 
.IP "\fB$PCP_PMDAS_DIR/dmcache/Remove\fR" 4 
undo installation script for the \fBpmdadmcache\fR agent 
.IP "\fB$PCP_LOG_DIR/pmcd/dmcache.log\fR" 4 
default log file for error messages from \fBpmdadmcache\fR 
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fR are used to parameterize
the file and directory names used by \fBPCP\fR. On each installation, the
file \fB/etc/pcp.conf\fR contains the local values for these variables. 
The \fB$PCP_CONF\fR variable may be used to specify an alternative 
configuration file, as described in \fIpcp.conf\fR(5).
.SH SEE ALSO
.BR pmcd (1)
and
.BR PCPIntro (1).
