#! /bin/sh
#
# Copyright (c) 2011 Aconex.  All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# Install the PostgreSQL PMDA
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=postgresql
perl_opt=true
daemon_opt=false

perl -e "use DBI" 2>/dev/null
if test $? -ne 0; then
    echo "Perl database interface (DBI) is not installed"
    status=1
    exit
fi

perl -e "use DBD::Pg" 2>/dev/null
if test $? -ne 0; then
    echo "Postgres database driver (DBD::Pg) is not installed"
    status=1
    exit
fi

pmdaSetup
pmdaInstall
exit
