#! /bin/sh
#
# Copyright (c) 2016, 2023 Red Hat.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# Install the LLC PMDA and/or PMNS
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

if [ ! -d /sys/fs/resctrl/mon_data ] ; then
    VENDOR=$(lscpu | awk '/^Vendor ID/ {print $3}')
    case "$VENDOR" in
	*Intel*)
	    mount -t resctrl resctrl -o mba_MBps /sys/fs/resctrl
	    STATUS=$?
	    ;;
	*AMD*)
	    mount -t resctrl resctrl -o cdp /sys/fs/resctrl
	    STATUS=$?
	    ;;
	*)
	    STATUS=1
    esac
    if [ $STATUS -eq 0 ] ; then
	echo "Mounted /sys/fs/resctrl/mon_data"
    elif [ -z "$PCP_LLC_DIR" -o ! -d $PCP_LLC_DIR/mon_data ] ; then
	echo "last level cache metrics are not supported"
	exit 1
    fi
fi

iam=llc
dso_opt=true

pmdaSetup
pmdaInstall
exit 0
