'\"! tbl | mmdoc
'\"macro stdmacro
.\"
.\" Man page for pcp-nfsiostat
.\" Copyright (c) 2023 Oracle and/or its affiliates.
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"

.TH PCP-NFSIOSTAT 1 "PCP" "Performance Co-Pilot"

.SH NAME
\f3pcp-nfsiostat\f1 \- Emulate iostat for NFS mount points using /proc/self/mountstats

.SH SYNOPSIS
\fBpcp\fP [\fBpcp options\fP] \fBnfsiostat\fP [\fB-s\fP \fBsamples\fP] [\fB-a\fP \fBarchive\fP] [\fB-Z\fP \fB--timezone\fP] [\fB-z\fP \fB--hostzone\fP] [\fB-V\fP \fBVersion\fP]

.SH DESCRIPTION
The\fB pcp-nfsiostat \fPcommand reports client-side\fB Network File System (NFS) \fPI/O statistics for each mounted NFS filesystem. For every NFS mountpoint, the output consists of a summary section followed by detailed read and write statistics blocks. These statistics include operation rates, data throughput, latency, retransmissions, queueing delays, and error counts. By default,\fB pcp-nfsiostat \fPmonitors NFS mountpoints on the local host and reports live metrics collected via the \fB PCP NFS PMDA\fP. When an archive is specified, historical metrics are reported instead.

.SH OUTPUT FORMAT
Statistics are reported per mounted NFS filesystem using the following layout:

.nf
server:/export mounted on /mount/point:

           ops/s       rpc bklog
           0.017           0.000

read:              ops/s   kB/s   kB/op   retrans   avg RTT (ms)   avg exe (ms)   avg queue (ms)   errors
                   ...

write:             ops/s   kB/s   kB/op   retrans   avg RTT (ms)   avg exe (ms)   avg queue (ms)   errors
                   ...
.fi

.SH FIELD DESCRIPTIONS
.TP
.B ops/s
Number of NFS operations performed per second.

.TP
.B rpc bklog
Average number of RPC requests waiting to be transmitted.

.TP
.B kB/s
Kilobytes transferred per second.

.TP
.B kB/op
Average number of kilobytes transferred per operation.

.TP
.B retrans
Number of RPC retransmissions and the retransmission percentage.

.TP
.B avg RTT (ms)
Average round-trip time in milliseconds for RPC requests.

.TP
.B avg exe (ms)
Average execution time in milliseconds spent servicing requests on the server.

.TP
.B avg queue (ms)
Average time in milliseconds spent waiting in the RPC transmission queue.

.TP
.B errors
Number of failed operations and failure percentage.

.SH OPTIONS
.TP
.BR \-a ", " \-\-archive " " I archive
Fetch NFS I/O statistics from the specified PCP archive.

.TP
.BR \-s ", " \-\-samples " " I samples
Number of samples to collect before exiting.

.TP
.BR \-z ", " \-\-hostzone
Set the reporting timezone to the local timezone of the metrics source.

.TP
.BR \-Z ", " \-\-timezone " " I tz
Set the reporting timezone.

.TP
.BR \-V ", " \-\-version
Display version information and exit.

.TP
.BR \-? ", " \-\-help
Display usage information and exit.

.SH NOTES
.B pcp-nfsiostat
reports client-side NFS statistics collected from the kernel and exposed
via the PCP NFS PMDA. The output format and metrics are similar to those
reported by the
.BR nfsiostat (1)
tool from the nfs-utils package.

.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fP are used to parameterize
the file and directory names used by PCP.
On each installation, the
file \fI/etc/pcp.conf\fP contains the local values for these variables.
The \fB$PCP_CONF\fP variable may be used to specify an alternative
configuration file, as described in
.BR pcp.conf (5).

For environment variables affecting PCP tools, see
.BR pmGetOptions (3).

.SH SEE ALSO
.BR PCPIntro (1),
.BR pcp (1),
.BR nfsiostat (1),
.BR environ (7).
