'\"! tbl | mmdoc
'\"macro stdmacro
.\"
.\" Copyright (c) 2000-2004 Silicon Graphics, Inc.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PCP.ENV 5 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pcp.env\f1 \- script to set Performance Co-Pilot run-time environment variables
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.I /etc/pcp.env
.SH DESCRIPTION
The
.I pcp.env
script is sourced by assorted Performance Co-Pilot (PCP) scripts
and utilities to define the PCP operating environment variables.
The conjugate for executable programs using the PCP libraries is the
.IR __pmGetConfig (3)
function.
.PP
Typical usage of
.I pcp.env 
in a script is as follows :
.IP 
  #! /bin/sh

  # source the PCP environment variables
  . /etc/pcp.env
  rest of script ...

.PP
The full syntax and semantics of the
.I pcp.conf
file and the
.I __pmGetConfig
function are described in their respective reference pages.
.SH ENVIRONMENT
The
.B PCP_CONF
environment variable specifies an alternative path to the
.I pcp.conf
file.
.SH SEE ALSO
.BR PCPIntro (1),
.BR PCPIntro (3),
.BR PMAPI (3),
.BR __pmGetConfig (3)
and
.BR pcp.conf (5).
