'\"! tbl | mmdoc
'\"macro stdmacro
.\"
.\" Copyright (c) 2014 Joe White.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PERFEVENT.CONF 5 "PCP" "Performance Co-Pilot"
.SH NAME
\f3perfevent.conf\f1 \- the Performance Co-Pilot perfevent PMDA configuration file
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.I $PCP_PMDAS_DIRS/perfevent/perfevent.conf
.SH DESCRIPTION
The perfevent.conf configuration file defines which hardware performance counters
are enabled by the perfevent PMDA.
.PP
The configuration file contains a list of events that should be enabled for
each PMU. The perfevent PMDA detects which PMUs present and programs the
configured events. If multiple PMUs are available, the
perfevent PMDA uses the order of the entries in the configuration file to
determine which PMU settings to use. The entries at the top of the
configuration file have higher precidence.  Only one PMU configuration setting
is used.
.SH FILE FORMAT
The file consists of one or more groups of PMUs and the events that go with them.
.PP
The PMU identification string is enclosed in brackets and one or more events are listed below, one per line.
.PP
.RS
.B ["PMU identification string"]
.RE
.RS
.B EVENT_NAME [CPU OPTION]
.RE
.RS
.B ...
.RE
.PP
The available event cpu options are as follows:
.TP
.B cpu 
to add the counter to all cpus in the system 
.TP
.B cpu_rr 
to add to one of the cpus in a round-robin allocation strategy
.TP
.B node
to add the counter to the first cpu in each numa node
.TP
.B node_rr
to add the counter to the cpus in each numa node in a round-robin allocation strategy
.TP
.B [N] 
where N is the numerical digit of the CPU index
.PP
if the CPU option is absent then the event is programmed on all cpus.
.PP
Blank lines are ignored. Lines that begin with the # sign are ignored.
.PP
Multiple, comma separated, PMUs may be specified in the PMU definition.
.SH SEE ALSO
.BR pmdaperfevent (1).
