'\"macro stdmacro
.\"
.\" Copyright (c) 2018 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMDAPODMAN 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdapodman\f1 \- podman container performance metrics domain agent (PMDA)
.SH SYNOPSIS
\f3$PCP_PMDAS_DIR/podman/pmdapodman\f1
[\f3\-d\f1 \f2domain\f1]
[\f3\-l\f1 \f2logfile\f1]
.SH DESCRIPTION
.BR podman (1)
is a utility for managing pods, containers and container
images, following the container pod concept popularized by
Kubernetes.
.B pmdapodman
is a Performance Metrics Domain Agent (PMDA) which extracts
performance metrics describing the state of containers and
pods managed by podman.
.PP
The
.B podman
PMDA exports metrics that measure information about individual
containers and groups of containers, called pods.
.PP
A brief description of the
.B pmdapodman
command line options follows:
.TP 5
.B \-d
It is absolutely crucial that the performance metrics
.I domain
number specified here is unique and consistent.
That is,
.I domain
should be different for every PMDA on the one host, and the same
.I domain
number should be used for the same PMDA on all hosts.
.TP
.B \-l
Location of the log file.  By default, a log file named
.I podman.log
is written in the current directory of
.BR pmcd (1)
when
.B pmdapodman
is started, i.e.
.BR $PCP_LOG_DIR/pmcd .
If the log file cannot
be created or is not writable, output is written to the standard error instead.
.SH INSTALLATION
The
.B podman
PMDA is installed and available by default on Linux.
If you want to undo the installation, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/podman
# ./Remove
.in
.fi
.ft 1
.PP
If you want to establish access to the names, help text and values for the podman
performance metrics once more, after removal, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/podman
# ./Install
.in
.fi
.ft 1
.PP
.B pmdapodman
is launched by
.BR pmcd (1)
and should never be executed directly.
The Install and Remove scripts notify
.BR pmcd (1)
when the agent is installed or removed.
.SH FILES
.PD 0
.TP 10
.B $PCP_PMCDCONF_PATH
command line options used to launch
.B pmdapodman
.TP 10
.B $PCP_PMDAS_DIR/podman/help
default help text file for the podman metrics
.TP 10
.B $PCP_PMDAS_DIR/podman/Install
installation script for the
.B pmdapodman
agent
.TP 10
.B $PCP_PMDAS_DIR/podman/Remove
undo installation script for the 
.B pmdapodman
agent
.TP 10
.B $PCP_LOG_DIR/pmcd/podman.log
default log file for error messages and other information from
.B pmdapodman
.PD
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH SEE ALSO
.BR PCPIntro (1),
.BR pmcd (1),
.BR podman (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).
