#! /bin/sh
#
# Copyright (c) 2011-2013 Red Hat Inc.
# Copyright (c) 1997 Silicon Graphics, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# Install the systemd PMDA and/or PMNS
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=systemd
pmda_interface=6
pipe_opt=true
daemon_opt=true

# On some platforms, the 'adm' user does not exist, so the pmda needs
# to run as root, to get full access to the systemd journal
whoami=`which whoami 2>/dev/null`
haveadm="`su adm -s $whoami 2>/dev/null`"
if [ "x$haveadm" != "xadm" ]; then
    args="-Uroot"
    echo "Warning: user adm not found, running pmda as root"
    echo
else
    args=
fi

pmdaSetup
pmdaInstall

exit 0
