#!/bin/sh
# PCP QA Test No. 078
# $Revision: 2.11 $
# -z and -Z for pmdumplog
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter

tmp=/tmp/$$
trap "rm -f $tmp.*; exit" 0 1 2 3 15

# need a constant archive for this ...
ARCH=src-oss/babylon.percpu

# real QA test starts here
echo "Dump first 128 bytes ..."
dd bs=128 count=1 if=$ARCH.0 2>/dev/null | od -c -j 020

echo ""
TZ=EST-11
export TZ
echo "Local time, TZ=$TZ"
pmdumplog -l $ARCH

echo ""
TZ=""
echo "GMT time, TZ is empty"
pmdumplog -l $ARCH

echo ""
echo "-Z UTC"
pmdumplog -l -Z UTC $ARCH

echo ""
echo "-Z PDT8"
pmdumplog -l -Z PDT8 $ARCH

echo ""
echo "local time at collection host"
pmdumplog -lz $ARCH
