#! /bin/sh
# PCP QA Test No. 126
# on linux only, check /proc/net/snmp is what we're expecting
#
# Copyright (c) 2002 Silicon Graphics, Inc.  All Rights Reserved.
# 

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=0	# success is the default!
$sudo rm -rf $tmp.*
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here

if [ -e /proc/net/snmp ]
then
    awk '$2 !~ /[0-9]/ {print}' /proc/net/snmp
else
    grep -v '^QA' $seq.out
fi

# success, all done
exit $status
