#! /bin/sh
# PCP QA Test No. 170
# $Revision: 2.12 $
# Test $PCP_RC_DIR/pcp script pmcd log location
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.product
. ./common.check
. ./common.filter

tmp=/tmp/$$
status=1

_cleanup()
{
    [ -f $tmp.options ] && ./sudo mv $tmp.options $PCP_PMCDOPTIONS_PATH
    ./sudo rm -f $tmp.*
    ./sudo "$PCP_RC_DIR/pcp start" | _filter_pcp_start
    _wait_for_pmcd
    _wait_for_pmlogger
    exit $status
}

trap _cleanup 0 1 2 3 15

# real QA test starts here

rm -rf $tmp.*
echo "First, the standard logfile:"
./sudo "$PCP_RC_DIR/pcp start" >$tmp.out
_wait_for_pmcd
_wait_for_pmlogger
grep 'logfile is' $tmp.out | _filter_pcp_start
echo ""

cp $PCP_PMCDOPTIONS_PATH $tmp.options
cat <<End-Of-File >>$tmp.extras
# Dummy lines added by PCP QA test 170
#
-l $tmp.1.pmcd.log
-l $tmp.2.pmcd.log
End-Of-File
./sudo "cat $tmp.extras >>$PCP_PMCDOPTIONS_PATH"

echo "The logfile from the hacked \$PCP_PMCDOPTIONS_PATH (pmcd.options):"
./sudo "$PCP_RC_DIR/pcp start" >$tmp.out
_wait_for_pmcd
_wait_for_pmlogger
grep 'logfile is' $tmp.out | sed -e "s/$$/MYPID/" | _filter_pcp_start
[ ! -f $tmp.2.pmcd.log ] && echo "$PCP_PMCDOPTIONS_PATH log file ignored!"

status=0
exit
