#! /bin/sh
# PCP QA Test No. 253 (formerly 253, 294)
# $Revision: 1.12 $
# pmdumptext problems
# Bug #505832
#
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# creator
owner=kenmcd

seq=`basename $0`

if which pmdumptext >/dev/null 2>&1
then
    :
else
    echo "No pmdumptext binary installed" >$seq.notrun
    echo "$seq: [not run] `cat $seq.notrun`"
    exit 0
fi

echo "QA output created by $seq"

# get standard filters
. ./common.filter
. ./common.check

tmp=/tmp/$$
sudo=`pwd`/sudo
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
inst=`pminfo -F proc.psinfo.pid \
      | sed -n -e '/inst \[1 /{
s/^[^"]*"//
s/ .*//
p
}'`

if [ -z "$inst" ]
then
    echo "Arrgh, cannot find proc.psinfo.pid for init!"
    pminfo -F proc.psinfo.pid
fi

echo "proc.psinfo.pid[$inst] 0" >$tmp.config
echo "proc.psinfo.pid[1]" >> $tmp.config

pmdumptext -g -s 1 -f '' -t 1 -c $tmp.config >$tmp.out 2>&1

echo
echo "expect two \"1\"s ..."
sort -u $tmp.out

# success, all done
status=0
exit
