#! /bin/sh
# PCP QA Test No. 284
# $Revision: 1.12 $
# Run pducheck using purify
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.

# creator
owner=kenmcd

seq=`basename $0`

# get standard filters
. ./common.product
. ./common.filter
. ./common.check

_check_purify src-oss/pducheck

echo "QA output created by $seq"

tmp=/tmp/$$
sudo=`pwd`/sudo
status=1	# failure is the default!
trap "cd; rm -rf $tmp; exit \$status" 0 1 2 3 15

# real QA test starts here

_setup_purify src-oss/pducheck
_run_purify

# all done
status=0
exit
