#! /bin/sh
# PCP QA Test No. 331
# $Revision: 1.11 $
# Interp mode (similar to qa/093, but with purify)
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.

# creator
owner=kenmcd

seq=`basename $0`

# get standard filters
. ./common.product
. ./common.filter
. ./common.check

_filter()
{
    $PCP_AWK_PROG '
BEGIN			{ skip = 1 }
/ Purify /		{ skip = 0 }
/^FIU/			{ skip = 2; next }
/^[^ 	]/ && skip == 2	{ skip = 0 }
skip == 0		{ print }'
}

_check_purify src-oss/interp2

echo "QA output created by $seq"

tmp=/tmp/$$
here=`pwd`
sudo=$here/sudo
status=1	# failure is the default!
trap "cd /; rm -rf $tmp; exit \$status" 0 1 2 3 15

# real QA test starts here
_setup_purify src-oss/interp2

for arch in src-oss/bigbin src-oss/mv-bigbin src-oss/noti-foo
do
    echo
    echo "=== $arch ==="
    _run_purify -a $here/$arch | _filter
done

# all done
status=0
exit
