#!/bin/sh
# PCP QA Test No. 350
#
# help text malloc/free snarfoo ... found prior to 3.2 release
#
# Copyright (c) 2010 Ken McDonell.  All Rights Reserved.

# creator
owner=kenj

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

seq=`basename $0`

echo "QA output created by $seq"

tmp=/tmp/$$
here=`pwd`
sudo=$here/sudo
status=0	# success is the default!
$sudo rm -rf $tmp.* $seq.full
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

_filter()
{
    sed -e 's/ value [0-9][0-9]*/ value N/'
}

# real QA test starts here
pminfo -f simple | _filter
pminfo -T simple | _filter
pminfo -f simple | _filter
pminfo -t simple | _filter

# success, all done
exit
