#!/bin/sh
# PCP QA Test No. 437
# Exercise compressed archive files - badness in the uncompression
#
# Copyright (c) 2010 Ken McDonell.  All Rights Reserved.
#

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

seq=`basename $0`

echo "QA output created by $seq"

status=0	# success is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "cd $here; rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15
mkdir $tmp
export PATH=$tmp:$PATH
cd $tmp
touch null.0.bz2 null.index null.meta

_filter()
{
    sed -e '/uncompress using:/s/>.*/>LIBTMP/'
}

# real QA test starts here
cat <<End-of-File >bzcat
#!/bin/sh
exit 1
End-of-File
chmod 755 bzcat
pminfo -Dlog -a null 2>&1 | _filter

cat <<End-of-File >bzcat
#!/bin/sh
kill -KILL \$\$
End-of-File
chmod 755 bzcat
pminfo -Dlog -a null 2>&1 | _filter

# success, all done
exit
