#!/bin/sh
# PCP QA Test No. 452
# exercise dependencies between Linux PMDA clusters
# e.g. CLUSTER_CPUINFO needs cpu indom initialized by CLUSTER_STAT
#
# Copyright (c) 2011 Red Hat, Inc.  All Rights Reserved.
#

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

seq=`basename $0`

echo "QA output created by $seq"

status=0	# success is the default!
$sudo rm -rf $tmp.* $seq.full
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here

# CLUSTER_CPUINFO needs cpu indom initialized by CLUSTER_STAT
# without the fix, this will abort()
pminfo -L -f hinv.cpu.clock >/dev/null
status=$?

# success, all done
exit
