#! /bin/sh
# PCP QA Test No. 575
# exercise fix for bug #692244
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

signal=$PCP_BINADM_DIR/pmsignal
status=1	# failure is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
$sudo $signal -a pmie >/dev/null 2>&1
$sudo rm -fr $PCP_TMP_DIR/pmie
$sudo $PCP_RC_DIR/pmie stop \
| _filter_pcp_stop \
| sed -e "s;$PCP_RC_DIR;\$PCP_RC_DIR;g"

$sudo $PCP_RC_DIR/pmie start >/dev/null 2>&1
# success, all done
status=0
exit
