#! /bin/sh
# PCP QA Test No. 593
# $Revision: 1.6 $
# test pmlogger bug 779495
#
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# creator
owner=dxm

seq=`basename $0`

. ./localconfig
if [ $PCP_VER -lt 2200 -o \( $PCP_EOE_VER -ge 6500 -a $PCP_EOE_VER -lt 6508 \) -o $PCP_EOE_VER -lt 2200 ]
then
    echo "needs sample.many metrics & new pmlogger (pv#779495)" >$seq.notrun
    echo "$seq: [not run] `cat $seq.notrun`"
    exit 0
fi

echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

cleanup()
{
	pmstore sample.many.count 5
}

tmp=/tmp/$$
here=`pwd`
trap "cleanup ; rm -f $tmp.*; exit \$status" 0 1 2 3 15
status=1

# real QA test starts here

# if bug 779495 is outstanding, we'll fail a calloc

pmstore sample.many.count 30000

cat > $tmp.config << EOF
log mandatory on once {
	sample.many.int
}
EOF

pmlogger -l /dev/fd/1 -s 1 -c $tmp.config $tmp | _filter_pmlogger_log 

status=0
exit
