#! /bin/sh
# PCP QA Test No. 640
# $Revision: 1.5 $
# setuid root exploit with pmpost
# pv:827972
#
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# creator
owner=kenmcd

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

tmp=/tmp/$$
here=`pwd`
sudo=$here/sudo
status=0	# success is the default!
trap "$sudo rm -f $tmp.*; exit \$status" 0 1 2 3 15
$sudo cp /etc/passwd $tmp.passwd

_filter()
{
    # map the IRIX message to the Linux message to avoid
    # multiple *.out files
    #
    sed \
	-e 's;Unknown user id: r00t;/bin/su: user r00t does not exist;' \
	-e 's;Unknown id: r00t;/bin/su: user r00t does not exist;'
}

# real QA test starts here

src-oss/pmpost-exploit `which pmpost` >$tmp.out 2>&1
sts=$?
_filter <$tmp.out
if [ $sts = 0 ]
then
    echo "Success from src-oss/pmpost-exploit"
else
    echo "Failure from src-oss/pmpost-exploit"
fi

if diff /etc/passwd $tmp.passwd
then
    :
else
    echo "Arrgh ... /etc/passwd was altered! ... restoring it"
    $sudo cp $tmp.passwd /etc/passwd
fi

# success, all done
exit
