#!/bin/sh
# PCP QA Test No. 706
# $Revision: 1.7 $
# Interleaved pmLookupDesc() and pmFetch() across multiple PMDAs ...
# trying to reproduce PMDA failure on www.sgi.com
#
owner=ania
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`

. ./common.pcpweb

if [ ! -d $PCP_PMDAS_DIR/weblog ]
then
    echo "weblog PMDA not installed" >$seq.notrun
    echo "$seq: [not run] `cat $seq.notrun`"
    exit 0
fi

echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

tmp=/tmp/$$
status=1	# failure is the default!

_cleanup()
{
    _restore_state
    rm -f $tmp.*
    exit $status
}
trap _cleanup 0 1 2 3 15

# real QA test starts here

_save_state
_require_pmda weblog

for i in 1 2 3 4
do
    src-oss/multifetch -s 100 >$tmp.$i 2>&1 &
    src-oss/multifetch -s 100 >$tmp.$i 2>&1 &
    src-oss/multifetch -s 100 >$tmp.$i 2>&1 &
    src-oss/multifetch -s 100 >$tmp.$i 2>&1 &
done

wait

for i in 1 2 3 4
do
    echo
    echo "Log for multifetch #$i:"
    cat $tmp.$i
done

wait

status=0
exit
