#!/bin/sh
#
# find metrics in the QA archives
#

tmp=/tmp/$$
trap "rm -f $tmp.*; exit 0" 0 1 2 3 15

pat=""
for arg
do
    if [ -z "$pat" ]
    then
	pat="($arg)"
    else
	pat="$pat|($arg)"
    fi
done

for arch in src-oss/*.0
do
    pminfo -a $arch 2>&1 | egrep "$pat" >$tmp.out

    if [ -s $tmp.out ]
    then
	pmdumplog -l $arch >$tmp.info
	vers=`sed -n <$tmp.info -e '/Log Format Version/{
s/.*Version //
s/)//
p
}'`
	host=`sed -n <$tmp.info -e '/ from host /{
s/.* from host //
p
}'`
	echo "`basename $arch .0` (V.$vers) host: $host"
	grep commencing $tmp.info
	grep ending $tmp.info
	sed -e 's/^/    /' <$tmp.out
    fi
done
