#!/bin/sh
#
# Copyright (c) 2021 Red Hat.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# Install the sockets PMDA
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=sockets
pmns_name=network.persocket	# differs to PMDA name

which ss >/dev/null 2>&1
if [ $? -ne 0 ]
then
    echo "Error: 'ss' utility not found, cannot proceed."
    echo "You may need to install the 'iproute' package."
    status=1
    exit
fi

pmdaSetup
pmdaInstall

exit
