#! /bin/sh
#
# Copyright (c) 2021 Red Hat.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
#

. $PCP_DIR/etc/pcp.env

if grep -q "^sockets.*dso.*\.so" "$PCP_PMCDCONF_PATH" 2>/dev/null
then
    # migrate from dso to daemon
    sed -i '/^sockets/d' "$PCP_PMCDCONF_PATH"
    touch "$PCP_PMDAS_DIR/sockets/.NeedInstall"
fi

exit 0
