'\"macro stdmacro
.\"
.\" Copyright (c) 2015 Martins Innus
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMDASLURM 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdaslurm\f1 \- SLURM statistics performance metrics domain agent (PMDA)
.SH DESCRIPTION
\f3pmdaslurm\f1 is a Performance Metrics Domain Agent (\s-1PMDA\s0) which
exports metric values from the
slurm perlapi
interface to provide information on slurm jobs, nodes and users.
.SH INSTALLATION
Install the slurm PMDA by using the Install script as root:
.PP
      # cd $PCP_PMDAS_DIR/slurm
.br
      # ./Install
.PP
To uninstall, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/slurm
.br
      # ./Remove
.PP
\fBpmdaslurm\fR is launched by \fIpmcd\fR(1) and should never be executed 
directly. The Install and Remove scripts notify \fIpmcd\fR(1) when the 
agent is installed or removed.
.SH FILES
.IP "\fB$PCP_PMDAS_DIR/slurm/Install\fR" 4 
installation script for the \fBpmdaslurm\fR agent 
.IP "\fB$PCP_PMDAS_DIR/slurm/Remove\fR" 4 
undo installation script for the \fBpmdaslurm\fR agent 
.IP "\fB$PCP_LOG_DIR/pmcd/slurm.log\fR" 4 
default log file for error messages from \fBpmdaslurm\fR 
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fR are used to parameterize
the file and directory names used by \fBPCP\fR. On each installation, the
file \fB/etc/pcp.conf\fR contains the local values for these variables. 
The \fB$PCP_CONF\fR variable may be used to specify an alternative 
configuration file, as described in \fIpcp.conf\fR(5).
.SH SEE ALSO
.BR PCPIntro (1)
.BR Slurm (3)
and
.BR pmcd (1),
