#!/bin/sh
#
# Copyright (c) 2009 Aconex.  All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
# 
# Install the Bonding PMDA (bonded network interfaces)
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=bonding
perl_opt=true
daemon_opt=false
forced_restart=false

if ! test -d /sys/class/net; then
    echo "SYSFS not enabled in your kernel"
    exit 1
fi
if ! test -f /sys/class/net/bonding_masters; then
    echo "Bonding statistics unavailable (load bonding module)"
    exit 1
fi

pmdaSetup
pmdaInstall
exit 0
