# amdgpu PMDA rewriting rules
#

# -- start changes for PMNS errors and metdata corrections from initial release
#
# remap PMNS 162.2.0 had name of clock but metadata for temperature
# and retire old "millidegree" temperature metric (temperature is
# a float in degrees in the second version of the PMDA)
#
metric 162.2.0 {
    name -> amdgpu.gpu.old_temperature dupok
    pmid -> 162.3.5
}
text metric 162.2.3 all { metric -> 162.3.5 }
label item 162.2.3 { item -> 162.3.5 }

# remap PMNS 162.2.1 had name of clock_max but metadata for load
#
metric 162.2.1 {
    name -> amdgpu.gpu.load dupok
    pmid -> 162.3.1
}
text metric 162.2.2 * { metric -> 162.3.1 }
label item 162.2.2 * { item -> 162.3.1 }

# remap PMNS 162.2.2 had name of load but metadata for average_power
#
metric 162.2.2 {
    name -> amdgpu.gpu.average_power dupok
    pmid -> 162.3.2
}
text metric 162.2.4 * { metric -> 162.3.2 }
label item 162.2.4 * { item -> 162.3.2 }

# remap PMNS 162.2.3 had name of temperature but metadata for clock
# and change units for MHz
#
metric 162.2.3 {
    name -> amdgpu.gpu.clock dupok
    pmid -> 162.3.3
    units -> 0,-1,1,0,USEC,ONE
}
text metric 162.2.0 * { metric -> 162.3.3 }
label item 162.2.0 * { item -> 162.3.3 }

# remap PMNS 162.2.4 had name of average_power but metadata for clock_max
# and change units for MHz
#
metric 162.2.4 {
    name -> amdgpu.gpu.clock_max dupok
    pmid -> 162.3.4
    units -> 0,-1,1,0,USEC,ONE
}
text metric 162.2.1 * { metric -> 162.3.4 }
label item 162.2.1 * { item -> 162.3.4 }

# change units for MHz
#
metric amdgpu.memory.clock {
    units -> 0,-1,1,0,USEC,ONE
}

# change units for MHz
#
metric amdgpu.memory.clock_max {
    units -> 0,-1,1,0,USEC,ONE
}
#
# -- end changes for PMNS errors and metdata corrections from initial release

# changes for extra units (using new PMIDs)
#
metric 162.3.0 {
    extraunits -> 0,0,0,0,0,0,TEMPERATURE,C
}
metric 162.3.2 {
    extraunits -> 0,0,0,0,0,0,POWER,W
}
