.\" 
.\" Copyright (c) 2014, 2018 Red Hat.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.TH "PMDALMSENSORS" "1" "PCP" "Performance Co-Pilot" ""
.SH "NAME"
\f3pmdalmsensors.python\f1 \- Linux hardware monitoring performance metrics domain agent (PMDA)
.SH "SYNOPSIS"
\f3$PCP_PMDAS_DIR/lmsensors/pmdalmsensors.python\f1
[\f3debug\f1]
.SH "DESCRIPTION"
.B pmdalmsensors
is a Performance Metrics Domain Agent (PMDA) which extracts
performance metrics describing the state of hardware using
the lm\-sensors software on compatible motherboards.
.PP 
The
.B lmsensors
PMDA exports metrics that measure fan speeds and core temperatures.
.PP 
.SH "INSTALLATION"
If you want access to the names, help text and values for the lmsensors
performance metrics, do the following as root:
.PP 
.ft CW
.nf 
.in +0.5i
# cd $PCP_PMDAS_DIR/lmsensors
# ./Install
.in
.fi 
.ft 1
.PP 
If you want to undo the installation, do the following as root:
.PP 
.ft CW
.nf 
.in +0.5i
# cd $PCP_PMDAS_DIR/lmsensors
# ./Remove
.in
.fi 
.ft 1
.PP 
.B pmdalmsensors.python is launched by
.BR pmcd (1)
The Install and Remove scripts notify
.BR pmcd (1)
when the agent is installed or removed.
pmdalmsensors.python is usually not executed directly. For debugging
purposes, 'debug' in the script can be set to 1 or 2, and when then
running the script from command line, debug output is printed
to STDOUT. This should just be used when running the script maually
from the command line. To use the script from
.BR pmcd (1)
, the script has to contain 'debug = 0'.
.SH "FILES"
.PD 0
.TP 10
.B $PCP_PMCDCONF_PATH
command line options used to launch
.B pmdalmsensors
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/help
default help text file for the lmsensors metrics
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/Install
installation script for the
.B pmdalmsensors
agent
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/Remove
undo installation script for the 
.B pmdalmsensors
agent
.PD
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH "SEE ALSO"
.BR PCPIntro (1),
.BR pmcd (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).
