.\" 
.\" Copyright (c) 2014 Red Hat.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.TH "PMDALMSENSORS" "1" "PCP" "Performance Co-Pilot" ""
.SH "NAME"
\f3pmdalmsensors.perl\f1 \- Linux hardware monitoring performance metrics domain agent (PMDA)
.SH "SYNOPSIS"
\f3$PCP_PMDAS_DIR/lmsensors/pmdalmsensors.perl\f1
[\f3debug\f1]
.SH "DESCRIPTION"
.B pmdalmsensors
is a Performance Metrics Domain Agent (PMDA) which extracts
performance metrics describing the state of hardware using
the lm\-sensors on compatible motherboards.
.PP 
The
.B lmsensors
PMDA exports metrics that measure fan speeds and core temperatures.
.PP 
A brief description of the
.B pmdalmsensors
command line options follows:
.TP 5
.B debug
This option can be used for debug output. Usable when starting
the script from the commandline.
.SH "INSTALLATION"
If you want access to the names, help text and values for the lmsensors
performance metrics, do the following as root:
.PP 
.ft CW
.nf 
.in +0.5i
# cd $PCP_PMDAS_DIR/lmsensors
# ./Install
.in
.fi 
.ft 1
.PP 
If you want to undo the installation, do the following as root:
.PP 
.ft CW
.nf 
.in +0.5i
# cd $PCP_PMDAS_DIR/lmsensors
# ./Remove
.in
.fi 
.ft 1
.PP 
.B pmdalmsensors.perl is launched by
.BR pmcd (1)
and should not be executed directly.
The Install and Remove scripts notify
.BR pmcd (1)
when the agent is installed or removed.
.SH "FILES"
.PD 0
.TP 10
.B $PCP_PMCDCONF_PATH
command line options used to launch
.B pmdalmsensors
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/help
default help text file for the lmsensors metrics
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/Install
installation script for the
.B pmdalmsensors
agent
.TP 10
.B $PCP_PMDAS_DIR/lmsensors/Remove
undo installation script for the 
.B pmdalmsensors
agent
.TP 10
.B $PCP_LOG_DIR/pmcd/lmsensors.log
default log file for error messages and other information from
.B pmdalmsensors
.PD
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH "SEE ALSO"
.BR PCPIntro (1),
.BR pmcd (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).
