'\"macro stdmacro
.\"
.\" Copyright (c) 2017 Ronak Jain.
.\" Copyright (c) 2017 Red Hat Inc.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\"
.TH PMDAPROMETHEUS 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdaprometheus\f1 \- Prometheus PMDA
.SH DESCRIPTION
\fBpmdaprometheus\fR is a Performance Metrics Domain Agent (PMDA) which
creates PCP metrics from Prometheus endpoints, which provide HTTP based
access to application metrics.
.PP
Further details on the Prometheus exposition format can
be found at
.I https://prometheus.io/docs/instrumenting/exposition_formats

.SH SOURCES

As it runs,
.B pmdaprometheus
periodically scans the
.I $PCP_PMDAS_DIR/prometheus/urls.d
directory, looking for source url files (\c
.IR *.url).
Each .url file contains one complete HTTP or HTTPS URL at which to
pmdaprometheus is to reach a Prometheus endpoint.  The server does not
have to be up or stay running.  The pmda will relay data and metadata
when/if they are up, and will return errors when/if they are down.

.SH METRICS

All metrics from a file named
.IR FOO.url
will be exported as PCP metrics with the
.I prometheus.FOO.
prefix.  Therefore, the FOO name must be a valid component for PMNS metric
names.  If the FOO name has multiple dot-separated components, the resulting
PMNS names will present those components.  Users should avoid configurations
with sources that mix levels of nesting, such as
.IR FOO.BAR.url
.IR FOO.BAZ.url
.IR FOO.url
because metrics under FOO one may conflict with or hide FOO.BAR and FOO.BAZ
subtrees.


\" example
\" describe metric naming conventions
\" refer to pmwebd interop
\" describe # PCP extras

.SH LIMITATIONS

.B pmdaprometheus
and
.B libpcp
internals impose some numerical constraints about the number of sources (4095),
metrics (1024) within each source, and instance domain instances for each
metric (4194304).

\" errors 


.SH INSTALLATION
Install the Prometheus PMDA by using the Install script as root:
.PP
      # cd $PCP_PMDAS_DIR/prometheus
.br
      # ./Install
.PP
To uninstall, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/prometheus
.br
      # ./Remove
.PP
\fBpmdaprometheus\fR is launched by \fIpmcd\fR(1) and should never be executed
directly. The Install and Remove scripts notify \fIpmcd\fR(1) when the
agent is installed or removed.
.SH FILES
.IP "\fB$PCP_PMDAS_DIR/prometheus/Install\fR" 4
installation script for the \fBpmdaprometheus\fR agent
.IP "\fB$PCP_PMDAS_DIR/prometheus/Remove\fR" 4
undo installation script for the \fBpmdaprometheus\fR agent
.IP "\fB$PCP_PMDAS_DIR/prometheus/urls.d/\fR" 4
source files for the \fBpmdaprometheus\fR agent
.IP "\fB$PCP_LOG_DIR/pmcd/prometheus.log\fR" 4
default log file for error messages from \fBpmdaprometheus\fR
.IP "\fB$PCP_VAR_DIR/\fR" 4
directory containing internal tables for ID number persistence

.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fR are used to parameterize
the file and directory names used by \fBPCP\fR. On each installation, the
file \fB/etc/pcp.conf\fR contains the local values for these variables.
The \fB$PCP_CONF\fR variable may be used to specify an alternative
configuration file, as described in \fIpcp.conf\fR(5).
.SH SEE ALSO
.BR pmcd (1),
.BR pminfo (1),
.BR pmwebd (1),
and
.IR https://prometheus.io/docs/instrumenting/exposition_formats .
