'\"macro stdmacro
.\"
.\" Copyright (c) 2014-2018 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\"
.TH PMDADS389LOG 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdads389log\f1 \- 389 Directory Server Log PMDA
.SH DESCRIPTION
\fBpmdads389log\fP is a Performance Metrics Domain Agent (PMDA)
which extracts statistics from 389 Directory Server access log
using the \fBlogconv.pl\fP(1) utility.
.SH INSTALLATION
\fBpmdads389log\fP reads configuration file
.IP
.PD 0
.RS +4
.IP \(bu 2
.I \f(CW$PCP_PMDAS_DIR\fP/ds389log/ds389log.conf
.RE
.PD
.PP
This file can contain overridden values (Perl code) for the settings
listed at the start of
.IR pmdads389log.pl ,
namely:
.IP
.PD 0
.RS +4
.IP \(bu 2
\fBlogconv.pl\fR parameters
.IP \(bu
minimal query interval
.IP \(bu
389 DS access log to use
.IP \(bu
389 DS log directory to use (used if no file specified)
.IP \(bu
non-root user having read access to the access log file
.RE
.PD
.PP
Once this is setup, you can access the names and values for the
389 DS performance metrics by doing the following as root:
.sp 1
.RS +4
.ft B
.nf
# cd $PCP_PMDAS_DIR/ds389log
# ./Install
.fi
.ft P
.RE
.sp 1
To uninstall, do the following as root:
.sp 1
.RS +4
.ft B
.nf
# cd $PCP_PMDAS_DIR/ds389log
# ./Remove
.fi
.ft P
.RE
.sp 1
\fBpmdads389log\fP is launched by \fBpmcd\fP(1) and should never be
executed directly.
The Install and Remove scripts notify \fBpmcd\fP(1) when the
agent is installed or removed.
.SH FILES
.TP
.I \f(CW$PCP_PMDAS_DIR\fP/ds389log/ds389log.conf
configuration file for the \fBpmdads389log\fP agent
.TP
.I \f(CW$PCP_PMDAS_DIR\fP/ds389log/Install
installation script for the \fBpmdads389log\fP agent
.TP
.I \f(CW$PCP_PMDAS_DIR\fP/ds389log/Remove
undo installation script for the \fBpmdads389log\fP agent
.TP
.I \f(CW$PCP_LOG_DIR\fP/pmcd/ds389log.log
default log file for error messages from \fBpmdads389log\fP
.TP
.I /var/log/dirsrv/slapd\-.../access
389 Directory Server access log parsed by \fBlogconv.pl\fP
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fP are used to parameterize
the file and directory names used by PCP.
On each installation, the
file \fI/etc/pcp.conf\fP contains the local values for these variables.
The \fB$PCP_CONF\fP variable may be used to specify an alternative
configuration file, as described in \fBpcp.conf\fP(5).
.SH SEE ALSO
.BR PCPIntro (1),
.BR logconv.pl (1),
.BR pmcd (1)
and
.BR pmdads389 (1).
