#! /bin/sh
#
# Copyright (c) 2009 Josef 'Jeff' Sipek <jeffpc@josefsipek.net>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# Install the postfix PMDA
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=postfix
perl_opt=true
daemon_opt=false
forced_restart=true

which qshape >/dev/null 2>&1
if test $? -ne 0; then
    # no qshape executable, look for the Perl script in some obscure
    # places
    #
    for script in \
	/usr/share/doc/packages/postfix-doc/auxiliary/qshape/qshape.pl
    do
	if [ -f "$script" ]
	then
	    args="$script"
	    break
	fi
    done
    if [ -z "$args" ]
    then
	echo "Postfix qshape utility is not installed"
	exit 1
    fi
fi

pmdaSetup
pmdaInstall
exit 0
