'\"macro stdmacro
.\"
.\" Copyright (c) 2011 Aconex.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMDAPOSTFIX 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdapostfix\f1 \- Postfix performance metrics domain agent (PMDA)
.SH DESCRIPTION
\f3pmdapostfix\f1 is a Performance Metrics Domain Agent (\s-1PMDA\s0) which exports
mail queue sizes as reported by \fBqshape\fR\|(1), as well as aggregate statistics
collected from mail.log.
.SH INSTALLATION
If you want access to the names and values for the Postfix performance
metrics, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/postfix
.br
      # ./Install
.PP
To uninstall, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/postfix
.br
      # ./Remove
.PP
\fBpmdapostfix\fR is launched by \fBpmcd\fR(1) and should never be executed 
directly. The Install and Remove scripts notify \fBpmcd\fR(1) when the 
agent is installed or removed.
.SH FILES
.IP "\fB$PCP_PMDAS_DIR/postfix/Install\fR" 4 
installation script for the \fBpmdapostfix\fR agent 
.IP "\fB$PCP_PMDAS_DIR/postfix/Remove\fR" 4 
undo installation script for the \fBpmdapostfix\fR agent 
.IP "\fB$PCP_LOG_DIR/pmcd/postfix.log\fR" 4 
default log file for error messages from \fBpmdapostfix\fR 
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fR are used to parameterize
the file and directory names used by \fBPCP\fR. On each installation, the
file \fB/etc/pcp.conf\fR contains the local values for these variables. 
The \fB$PCP_CONF\fR variable may be used to specify an alternative 
configuration file, as described in \fIpcp.conf\fR(5).
.SH SEE ALSO
.BR pmcd (1)
and
.BR qshape (1).
