metric power.battery.capacity.design {
    extraunits -> 0,1,0,0,HOUR,0,CURRENT,mA
}

metric power.battery.capacity.max {
    extraunits -> 0,1,0,0,HOUR,0,CURRENT,mA
}

metric power.battery.voltage {
    extraunits -> 0,0,0,0,0,0,VOLTAGE,mV
}

metric power.battery.amperage {
    extraunits -> 0,0,0,0,0,0,CURRENT,mA
}
