#!gmake

ifdef PCP_CONF
include $(PCP_CONF)
else
include $(PCP_DIR)/etc/pcp.conf
endif
PATH	= $(shell . $(PCP_DIR)/etc/pcp.env; echo $$PATH)
include $(PCP_INC_DIR)/builddefs

TESTDIR = $(PCP_VAR_DIR)/testsuite/prometheus

default default_pcp setup: prometheus_client_server.python

install install_pcp:

include $(BUILDRULES)
