'\"macro stdmacro
.\"
.\" Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMCONTEXTUNDEF 3 "SGI" "Performance Co-Pilot"
.SH NAME
\f3pmContextUndef\f1 \- change current PMAPI context
.SH "C SYNOPSIS"
.ft 3
#include <pcp/pmapi.h>
.sp
void pmContextUndef(void)
.sp
cc ... \-lpcp
.ft 1
.SH DESCRIPTION
An application using the
Performance Metrics Application Programming Interface (PMAPI)
may manipulate several concurrent contexts,
each associated with a source of performance metrics, e.g. \c
.BR pmcd (1)
on some host, or an archive log of performance metrics as created by
.BR pmlogger (1).
.PP
Calling
.B pmContextUndef
causes the
current PMAPI context to be reset to undefined state which could be use
to prevent unintentional communication with PMCD.
.SH SEE ALSO
.BR PMAPI (3),
.BR pmDestroyContext (3),
.BR pmDupContext (3),
.BR pmNewContext (3)
and
.BR pmWhichContext (3).
