'\"macro stdmacro
.\"
.\" Copyright (c) 2021 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMDAZFS 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdazfs\f1 \- ZFS filesystem performance metrics domain agent (PMDA) for Linux
.SH SYNOPSIS
\f3$PCP_PMDAS_DIR/linux_zfs/pmdazfs\f1

