'\"macro stdmacro
.\"
.\" Copyright (c) 2021 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMDAZFS 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdazfs\f1 \- ZFS filesystem performance metrics domain agent (PMDA) for Linux
.SH SYNOPSIS
\f3$PCP_PMDAS_DIR/linux_zfs/pmdazfs\f1
[\f3\-d\f1 \f2domain\f1]
[\f3\-l\f1 \f2logfile\f1]
.SH DESCRIPTION
.B pmdazfs
is a Performance Metrics Domain Agent (PMDA) which extracts
performance metrics describing the state of the ZFS filesystem
from the stats files located in /proc.
.PP
The
.B zfs
PMDA exports metrics that measure information about caching (ARC, L2ARC, ZIL, VDEV),
buffering, RAIDZ, dnode operations and pools IO.
.PP
A brief description of the
.B pmdazfs
command line options follows:
.TP 5
.B \-d
The performance metrics
.I domain
number must be set to a unique value.
.TP
.B \-l
Location of the log file.
By default, a log file named
.I zfs.log
is written in the current directory of
.BR pmcd (1)
when
.B pmdazfs
is started, i.e.
.BR $PCP_LOG_DIR/pmcd .
If the log file cannot
be created or is not writable, output is written to the standard error instead.
.SH INSTALLATION
OpenZFS is not included in PCP, and has to be installed on the system
from the available packages or source.
Once OpenZFS is installed and configured, the stats files should appear
in /proc and PMDA can be added to PMCD using the Install script:
.PP
.ft CR
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/zfs
# ./Install
.in
.fi
.ft 1
.PP
To remove PMDA use the Remove script:
.PP
.ft CR
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/zfs
# ./Remove
.in
.fi
.ft 1
.SH SEE ALSO
.BR PCPIntro (1),
.BR pmcd (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).

.\" control lines for scripts/man-spell
.\" +ok+ linux_zfs pmdazfs OpenZFS RAIDZ dnode VDEV ZFS ZIL zfs
