typedef struct zfs_dbufstats {
	unsigned int cache_count;
	unsigned int cache_size_bytes;
	unsigned int cache_size_bytes_max;
	unsigned int cache_target_bytes;
	unsigned int cache_lowater_bytes;
	unsigned int cache_hiwater_bytes;
	unsigned int cache_total_evicts;
	unsigned int cache_level_0;
	unsigned int cache_level_1;
	unsigned int cache_level_2;
	unsigned int cache_level_3;
	unsigned int cache_level_4;
	unsigned int cache_level_5;
	unsigned int cache_level_6;
	unsigned int cache_level_7;
	unsigned int cache_level_8;
	unsigned int cache_level_9;
	unsigned int cache_level_10;
	unsigned int cache_level_11;
	unsigned int cache_level_0_bytes;
	unsigned int cache_level_1_bytes;
	unsigned int cache_level_2_bytes;
	unsigned int cache_level_3_bytes;
	unsigned int cache_level_4_bytes;
	unsigned int cache_level_5_bytes;
	unsigned int cache_level_6_bytes;
	unsigned int cache_level_7_bytes;
	unsigned int cache_level_8_bytes;
	unsigned int cache_level_9_bytes;
	unsigned int cache_level_10_bytes;
	unsigned int cache_level_11_bytes;
	unsigned int hash_hits;
	unsigned int hash_misses;
	unsigned int hash_collisions;
	unsigned int hash_elements;
	unsigned int hash_elements_max;
	unsigned int hash_chains;
	unsigned int hash_chain_max;
	unsigned int hash_insert_race;
	unsigned int metadata_cache_count;
	unsigned int metadata_cache_size_bytes;
	unsigned int metadata_cache_size_bytes_max;
	unsigned int metadata_cache_overflow;
} zfs_dbufstats_t;

void zfs_dbufstats_fetch(zfs_dbufstats_t *dbufstats, regex_t *rgx_row);
