'\"macro stdmacro
.\"
.\" Copyright (c) 2008 Aconex.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMDASYSTEMTAP 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdasystemtap\f1 \- systemtap performance metrics domain agent (PMDA)
.SH DESCRIPTION
\f3pmdasystemtap\f1 is a Performance Metrics Domain Agent (\s-1PMDA\s0)
which exports metric values from the Linux systemtap dynamic tracing toolkit.
.PP
This implementation uses the
.BR stap (1)
tool, which is a front-end to the systemtap toolkit.
.SH INSTALLATION
In order to access performance data exported by systemtap from
with PCP, it is necessary to perform two configuration steps.
.PP
Firstly, configure systemtap probes, and verify them with
.BR stap (1) .
These should be produced in a format that is easily parsed,
and then stored in the
.I $PCP_PMDAS_DIR/systemtap/probes.stp
file.
.PP
Then
.B pmdasystemtap
must be configured to extract the values from the text produced by
.BR stap .
Two example probes are implemented in the default systemtap PMDA
script - readdir and sync traces (see
.I $PCP_PMDAS_DIR/systemtap/pmdasystemtap.pl
for details).
.PP
      # cd $PCP_PMDAS_DIR/systemtap
.br
      # [ edit probes.stp, test /usr/bin/stap probes.stp ]
.br
      # [ edit pmdasystemtap.pl ]
.PP
Once this is setup, you can access the names and values for the
systemtap performance metrics by doing the following as root:
.PP
      # cd $PCP_PMDAS_DIR/systemtap
.br
      # ./Install
.PP
To uninstall, do the following as root:
.PP
      # cd $PCP_PMDAS_DIR/systemtap
.br
      # ./Remove
.PP
\fBpmdasystemtap\fR is launched by \fIpmcd\fR(1) and should never be executed 
directly. The Install and Remove scripts notify \fIpmcd\fR(1) when the 
agent is installed or removed.
.SH FILES
.IP "\fB$PCP_PMDAS_DIR/systemtap/probes.stp\fR" 4 
probe configuration file for \fBstap\fR(1), run by \fBpmdasystemtap\fR
.IP "\fB$PCP_PMDAS_DIR/systemtap/Install\fR" 4 
installation script for the \fBpmdasystemtap\fR agent 
.IP "\fB$PCP_PMDAS_DIR/systemtap/Remove\fR" 4 
undo installation script for the \fBpmdasystemtap\fR agent 
.IP "\fB$PCP_LOG_DIR/pmcd/systemtap.log\fR" 4 
default log file for error messages from \fBpmdasystemtap\fR 
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fR are used to parameterize
the file and directory names used by \fBPCP\fR. On each installation, the
file \fB/etc/pcp.conf\fR contains the local values for these variables. 
The \fB$PCP_CONF\fR variable may be used to specify an alternative 
configuration file, as described in \fIpcp.conf\fR(5).
.SH SEE ALSO
.BR PCPIntro (1),
.BR pmcd (1)
and
.BR stap (1).
