#! /bin/sh
#
# Copyright (c) 2013 Red Hat.
# Copyright (c) 1997 Silicon Graphics, Inc.  All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# Install the simple PMDA and/or PMNS
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=simple

dso_opt=true
perl_opt=true
python_opt=true
socket_opt=true
socket_inet_def=2078

# Set up the simple PMDA (domain 253) InDom cache
#
domain=`sed -n <domain.h -e '/define SIMPLE/{
s/[ 	]*$//
s/.*[ 	]//
p
}'`
if [ -z "$domain" ]
then
    echo "Arrgh ... cannot extract domain number from domain.h"
    status=1
    exit
fi
if [ -d $PCP_VAR_DIR/config/pmda ]
then
    if [ ! -f "$PCP_VAR_DIR/config/pmda/$domain.1" ]
    then
	# First time Install, initialize PMDA's indom cache file
	#
	if "$PCP_BINADM_DIR/indomcachectl" -u $PCP_USER -g $PCP_GROUP $domain.1
	then
	    :
	else
	    echo "Cannot create indom cache file"
	    echo "Failed on: $PCP_VAR_DIR/config/pmda/$domain.1"
	    status=1
	    exit
	fi
    fi
fi

pmdaSetup
pmdaInstall
exit
