# 
# Copyright (c) 2013 Red Hat.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 

SHELL	= /bin/sh
CC	= cc
CFLAGS	= -g

TARGETS	= acme mmvdump

default: 	$(TARGETS)

mmvdump:	mmvdump.c
	$(CC) $(CFLAGS) -o $@ $^ -lpcp

acme:	acme.c
	$(CC) $(CFLAGS) -o $@ $^ -lpcp_mmv -lpcp

clean:
	rm -f *.o

clobber:	clean
	rm -f $(TARGETS)
