#!/bin/sh
#
# Copyright 2001,2009 Silicon Graphics, Inc., All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

. $PCP_DIR/etc/pcp.env

cd $PCP_VAR_DIR/pmns

$PCP_SHARE_DIR/lib/lockpmns root
trap "$PCP_SHARE_DIR/lib/unlockpmns root; exit" 0 1 2 3 15

if [ -f mmv.new ]
then
    if pminfo -h localhost -n root mmv > /dev/null 2>&1
    then
	pmnsdel mmv > /dev/null 2>&1
    fi

    mv mmv.new mmv
    pmnsadd mmv > /dev/null 2>&1
fi

exit 0
