#!/bin/sh -e
#DEBHELPER#

for PMDA in dm nfsclient openmetrics ; do
    if ! grep -q "$PMDA/pmda$PMDA" /etc/pcp/pmcd/pmcd.conf
    then
        if test -d "/var/lib/pcp/pmdas/$PMDA"
        then
            touch "/var/lib/pcp/pmdas/$PMDA/.NeedInstall"
        fi
    fi
done

# increase default pmlogger recording frequency
if [ ! -e /run/systemd ] ; then
    sed -i 's/^\#\ PMLOGGER_INTERVAL.*/PMLOGGER_INTERVAL=10/g' /etc/default/pmlogger
fi

# auto-enable these usually optional pmie rules
pmieconf -c enable dmthin
