#!/bin/sh -e
#DEBHELPER#
touch /var/lib/pcp/pmns/.NeedRebuild
chmod 644 /var/lib/pcp/pmns/.NeedRebuild

getent group pcp >/dev/null || groupadd -r pcp
getent passwd pcp >/dev/null || \
  useradd -c "Performance Co-Pilot" -g pcp -d /var/lib/pcp -M -r -s /usr/sbin/nologin pcp
chown -R pcp:pcp /var/log/pcp/pmcd 2>/dev/null || true
chown -R pcp:pcp /var/log/pcp/pmie 2>/dev/null || true
chown -R pcp:pcp /var/log/pcp/pmproxy 2>/dev/null || true
chown -R pcp:pcp /var/log/pcp/pmlogger 2>/dev/null || true

update-rc.d pmcd defaults >/dev/null
update-rc.d pmlogger defaults >/dev/null
update-rc.d pmie defaults >/dev/null
update-rc.d pmproxy defaults >/dev/null

if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d pmcd start
    invoke-rc.d pmlogger start
else
    /etc/init.d/pmcd start
    /etc/init.d/pmlogger start
fi
