#
# Copyright (c) 2007 Nathan Scott.  All Rights Reserved.
#

TOPDIR = ..
include $(TOPDIR)/src/include/builddefs

PNGFILES  = $(shell echo *.png)
SVGFILES  = $(shell echo *.svg)
LSRCFILES = $(SVGFILES) $(PNGFILES)

default :

include $(BUILDRULES)

install : default
