#!/bin/sh
#
# C language lint checking, mainly for use in PCP CI builds.
# Usage: scripts/c-lint -I$(TOPDIR)/src/include/pcp <file>...
#
# Note: silently exits if 'cppcheck' utility is unavailable.
#

which cppcheck >/dev/null 2>&1
[ $? -eq 0 ] || exit 0	# not installed

args="--inline-suppr --force --quiet --error-exitcode=1"

# cppcheck mishandles glibc MAXNAMELEN/FILE_NAMELEN definition
args="$args --suppress=syntaxError:*/platform_defs.h"

if cppcheck --help | grep -- --library >/dev/null
then
    args="$args --library=posix"
else
    args="$args --std=posix"
fi

exec cppcheck $args "$@"
