'\"macro stdmacro
.\"
.\" Copyright (c) 2016 Fujitsu.
.\" Copyright (c) 2019 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\"
.TH PCP-IPCS 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pcp-ipcs\f1 \- provide information on IPC facilities
.SH SYNOPSIS
\f3pcp\f1 [\f2pcp\ options\f1] \f3ipcs\f1
[\f3\-luV?\f1] [\f2output\-format\f1]
.SH DESCRIPTION
.B pcp-ipcs
provides information on the inter-process communication facilities
for which the calling process has read access.
.SH OPTIONS
When invoked via the
.BR pcp (1)
command, the
.BR \-h /\c
.BR \-\-host ,
.BR \-a /\c
.BR \-\-archive ,
.BR \-O /\c
.BR \-\-origin ,
.BR \-Z /\c
.BR \-\-timezone
and several other
.I pcp options
become indirectly available; refer to
.BR PCPIntro (1)
for a complete description of these options.
.PP
The additional command line options available for
.B pcp-ipcs
are:
.\" .TP
.\" \fB\-i\fR \fIid\fR, \fB\-\-id\fR=\fIid\fR
.\" Print details only on the resource identified by
.\" .IR id .
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information and exit.
.TP
\fB\-?\fR, \fB\-\-help\fR
Display the usage message and exit.
.\" .SS "Resource options"
.\" .TP
.\" \fB\-q\fR, \fB\-\-queues\fR
.\" Write information about active message queues.
.\" .TP
.\" \fB\-m\fR, \fB\-\-shmems\fR
.\" Write information about active shared memory segments.
.\" .TP
.\" \fB\-s\fR, \fB\-\-semaphores\fR
.\" Write information about active semaphore sets.
.\" .TP
.\" \fB\-a\fR, \fB\-\-all\fR
.\" Write information about all three resources (default).
.SS "Output formats"
.\" Of these options only one takes effect: the last one specified.
.\" .TP
.\" \fB\-c\fR, \fB\-\-creator\fR
.\" Show creator and owner.
.TP
\fB\-l\fR, \fB\-\-limits\fR
Show resource limits.
.\" .TP
.\" \fB\-p\fR, \fB\-\-pid\fR
.\" Show PIDs of creator and last operator.
.\" .TP
.\" \fB\-t\fR, \fB\-\-time\fR
.\" Write time information.
.\" The time of the last control operation that changed
.\" the access permissions for all facilities, the time of the last
.\" .I msgsnd()
.\" and
.\" .I msgrcv()
.\" operations on message queues, the time of the last
.\" .I shmat()
.\" and
.\" .I shmdt()
.\" operations on shared memory, and the time of the last
.\" .I semop()
.\" operation on semaphores.
.TP
\fB\-u\fR, \fB\-\-summary\fR
Show status summary.
.\" .SS "Representation"
.\" These affect only the \fB\-l\fR (\fB\-\-limits\fR) option.
.\" .TP
.\" \fB\-b\fR, \fB\-\-bytes\fR
.\" Print sizes in bytes.
.\" .TP
.\" .B \-\-human
.\"Print sizes in human-readable format.
.SH PCP ENVIRONMENT
Environment variables with the prefix \fBPCP_\fP are used to parameterize
the file and directory names used by PCP.
On each installation, the
file \fI/etc/pcp.conf\fP contains the local values for these variables.
The \fB$PCP_CONF\fP variable may be used to specify an alternative
configuration file, as described in \fBpcp.conf\fP(5).
.PP
For environment variables affecting PCP tools, see \fBpmGetOptions\fP(3).
.SH SEE ALSO
.BR PCPIntro (1),
.BR pcp (1),
.BR ipcmk (1),
.BR ipcrm (1),
.BR msgrcv (2),
.BR msgsnd (2),
.BR semget (2),
.BR semop (2),
.BR shmat (2),
.BR shmdt (2)
and
.BR shmget (2).

.\" control lines for scripts/man-spell
.\" +ok+ [all of the following are SystemV SHM/SEM libc routines]
.\" +ok+ semget shmget msgrcv msgsnd semop shmat shmdt ipcmk ipcrm
.\" +ok+ ipcs [from pcp-ipcs]
