'\"macro stdmacro
.\"
.\" Copyright (c) 2014 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMDAROOMTEMP 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdaroomtemp\f1 \- room temperature performance metrics domain agent (PMDA)
.SH SYNOPSIS
\f3$PCP_PMDAS_DIR/roomtemp/pmdaroomtemp\f1
[\f3\-d\f1 \f2domain\f1]
[\f3\-l\f1 \f2logfile\f1]
.SH DESCRIPTION
.B pmdaroomtemp
is a Performance Metrics Domain Agent (PMDA) which exports the
temperature from one or more sensors built using the DS2480 and
DS1280 chipsets and MicroLAN technology from Dallas Semiconductor
Corporation.
.PP
The
.B roomtemp
PMDA exports metrics that reflect the temperatures from one or
more of these devices, in both degrees Celcius and Fahrenheit.
Each metric has one instance for each temperature sensor device.
The external instance identifiers are the serial numbers (in hex)
of the DS1280 chips discovered when the MicroLAN was probed.
.PP
A brief description of the
.B pmdaroomtemp
command line options follows:
.TP 5
.B \-d
It is absolutely crucial that the performance metrics
.I domain
number specified here is unique and consistent.
That is,
.I domain
should be different for every PMDA on the one host, and the same
.I domain
number should be used for the same PMDA on all hosts.
.TP
.B \-l
Location of the log file.  By default, a log file named
.I roomtemp.log
is written in the current directory of
.BR pmcd (1)
when
.B pmdaroomtemp
is started, i.e.
.BR $PCP_LOG_DIR/pmcd .
If the log file cannot
be created or is not writable, output is written to the standard error instead.
.SH INSTALLATION
If you want access to the names, help text and values for the roomtemp
performance metrics, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/roomtemp
# ./Install
.in
.fi
.ft 1
.PP
If you want to undo the installation, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/roomtemp
# ./Remove
.in
.fi
.ft 1
.PP
.B pmdaroomtemp
is launched by
.BR pmcd (1)
and should never be executed directly.
The Install and Remove scripts notify
.BR pmcd (1)
when the agent is installed or removed.
.SH FILES
.PD 0
.TP 10
.B $PCP_PMCDCONF_PATH
command line options used to launch
.B pmdaroomtemp
.TP 10
.B $PCP_PMDAS_DIR/roomtemp/help
default help text file for the roomtemp metrics
.TP 10
.B $PCP_PMDAS_DIR/roomtemp/Install
installation script for the
.B pmdaroomtemp
agent
.TP 10
.B $PCP_PMDAS_DIR/roomtemp/Remove
undo installation script for the 
.B pmdaroomtemp
agent
.TP 10
.B $PCP_LOG_DIR/pmcd/roomtemp.log
default log file for error messages and other information from
.B pmdaroomtemp
.PD
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH SEE ALSO
.BR PCPIntro (1),
.BR pmcd (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).
