'\"macro stdmacro
.\"
.\" Copyright (c) 2012,2014 Red Hat.
.\" Copyright (c) 2009 Aconex.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMCONFIG 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmconfig\f1 \- Performance Co-Pilot configuration parameters
.SH SYNOPSIS
\f3$PCP_BINADM_DIR/pmconfig\f1
[\f3\-a\f1|\f3-l\f1]
[\f3\-L\f1]
[\f3\-s\f1]
[\f2name ...\f1]
.SH DESCRIPTION
.B pmconfig
displays the values for some or all configuration parameters 
of the local Performance Co-Pilot toolkit installation.
.PP
The
.B \-L
option may be used to change the default reporting mode so that
the capabilities of the PCP library are reported, rather than the
PCP environment.
.PP
An output format suitable for sourcing in shell scripts can be
obtained using the
.B \-s
option, which ensures configuration information is quoted and
preceded by an export statement.
When not reporting the library capabilities, this mode will
produce a statement that does not override an existing setting
in the environment for PCP configuration variables.
.PP
In the default operating mode,
.B pmconfig
is often used in conjunction with the
.B $PCP_DIR
environment variable to setup scripts running under the Windows
operating system, where the filesystem hierarchy differs greatly
to the of Linux/UNIX-based operating systems.
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH SEE ALSO
.BR pmGetConfig (3),
.BR pcp.conf (5)
and
.BR pcp.env (5).
