'\"macro stdmacro
.\"
.\" Copyright (c) 2014 Red Hat.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.TH PMDANVIDIA 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmdanvidia\f1 \- nvidia gpu metrics domain agent (PMDA)
.SH SYNOPSIS
\f3$PCP_PMDAS_DIR/nvidia/pmdanvidia\f1
[\f3\-d\f1 \f2domain\f1]
[\f3\-l\f1 \f2logfile\f1]
.SH DESCRIPTION
.B pmdanvidia
is a Performance Metrics Domain Agent (PMDA) which extracts
performance metrics describing the metrics available on NVIDIA
GPU cards via the NVML library.
.PP
The
.B nvidia
PMDA exports metrics that measure gpu activity, memory utilization,
fan speed, etc on NVIDIA Tesla and Quadro cards.  Metrics are unlikely
to be available for consumer class cards.
.PP
A brief description of the
.B pmdanvidia
command line options follows:
.TP 5
.B \-d
It is absolutely crucial that the performance metrics
.I domain
number specified here is unique and consistent.
That is,
.I domain
should be different for every PMDA on the one host, and the same
.I domain
number should be used for the same PMDA on all hosts.
.TP
.B \-l
Location of the log file.  By default, a log file named
.I nvidia.log
is written in the current directory of
.BR pmcd (1)
when
.B pmdanvidia
is started, i.e.
.BR $PCP_LOG_DIR/pmcd .
If the log file cannot
be created or is not writable, output is written to the standard error instead.
.SH INSTALLATION
The
.B nvidia
PMDA is not installed and available by default.
If you want to undo the installation, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/nvidia
# ./Remove
.in
.fi
.ft 1
.PP
If you want to establish access to the names, help text and values for the nvidia
performance metrics once more, after removal, do the following as root:
.PP
.ft CW
.nf
.in +0.5i
# cd $PCP_PMDAS_DIR/nvidia
# ./Install
.in
.fi
.ft 1
.PP
.B pmdanvidia
is launched by
.BR pmcd (1)
and should never be executed directly.
The Install and Remove scripts notify
.BR pmcd (1)
when the agent is installed or removed.
.SH FILES
.PD 0
.TP 10
.B $PCP_PMCDCONF_PATH
command line options used to launch
.B pmdanvidia
.TP 10
.B $PCP_PMDAS_DIR/nvidia/help
default help text file for the nvidia metrics
.TP 10
.B $PCP_PMDAS_DIR/nvidia/Install
installation script for the
.B pmdanvidia
agent
.TP 10
.B $PCP_PMDAS_DIR/nvidia/Remove
undo installation script for the 
.B pmdanvidia
agent
.TP 10
.B $PCP_LOG_DIR/pmcd/nvidia.log
default log file for error messages and other information from
.B pmdanvidia
.PD
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH SEE ALSO
.BR PCPIntro (1),
.BR pmcd (1),
.BR pcp.conf (5)
and
.BR pcp.env (5).
