'\"macro stdmacro
.\"
.\" Copyright (c) 2000 Silicon Graphics, Inc.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMHOSTNAME 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmhostname\f1 \- report hostname
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.B $PCP_BINADM_DIR/pmhostname
[\fIhostname\fR]
.SH DESCRIPTION
.B pmhostname
reports the name of the host
.I hostname
as returned by
.BR gethostbyname (3).
.PP
If
.I hostname
is not specified, then the local host name
is retrieved using
.BR gethostname (2)
and this is than passed to
.BR gethostbyname (3).
.PP
.B pmhostname
provides a service for shell scripts that
mimics the logic formerly used by Performance Co-Pilot applications
when trying to determine the official name of a host.  PCP applications
no longer use DNS-based heuristics, and therefore this command is
.IR deprecated .
.PP
If
.BR gethostbyname (3)
fails, the input host name (either
.I hostname
or the result from calling
.BR gethostname (2))
is reported.
.SH "PCP ENVIRONMENT"
Environment variables with the prefix
.B PCP_
are used to parameterize the file and directory names
used by PCP.
On each installation, the file
.I /etc/pcp.conf
contains the local values for these variables.
The
.B $PCP_CONF
variable may be used to specify an alternative
configuration file,
as described in
.BR pcp.conf (5).
.SH SEE ALSO
.BR named (1),
.BR nsd (1),
.BR nslookup (1),
.BR gethostname (2),
.BR gethostbyname (3),
.BR pcp.conf (5),
.BR pcp.env (5)
and
.BR resolver (5).
