'\"macro stdmacro
.\"
.\" Copyright (c) 2007 Silicon Graphics, Inc.  All Rights Reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\"
.TH PMSLEEP 1 "PCP" "Performance Co-Pilot"
.SH NAME
\f3pmsleep\f1 \- portable subsecond-capable sleep
.\" literals use .B or \f3
.\" arguments use .I or \f2
.SH SYNOPSIS
.B $PCP_BINADM_DIR/pmsleep
.I interval
.SH DESCRIPTION
.B pmsleep
sleeps for 
.I interval.
The
.I interval
argument follows the syntax described in
.BR PCPIntro (1)
for 
.B \-t,
and in the simplest form may be an unsigned integer 
or floating point constant 
(the implied units in this case are seconds).
.SH DIAGNOSTICS
The exit status is 0 for success, or 1 for a malformed command line.
If the underlying
.B nanosleep (2)
system call fails, an errno is returned.
.SH SEE ALSO
.BR sleep (1),
.BR nanosleep (3).
