# darwin_proc PMDA rewriting rules
#

# proc.memory.size and proc.memory.rss values have always been
# stored in Kbytes; fix the metadata to match (was BYTE, now KBYTE)
#
metric proc.memory.size { units -> 1,0,0,KBYTE,0,0 }
metric proc.memory.rss { units -> 1,0,0,KBYTE,0,0 }
