#!/bin/sh
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
# 
# Contact information: Silicon Graphics, Inc., 1500 Crittenden Lane,
# Mountain View, CA 94043, USA, or: http://www.sgi.com
#
# Lock the PMNS against concurrent transactional updates
#
# $Revision: 1.8 $
#

. /etc/pcp.env

lock=${1-$PCP_VAR_DIR/pmns/root}.lock

i=0
while true
do
    if pmlock $lock
    then
	# lock acquired
	#
	#DEBUG# echo "pmnslock: `date; ls -li $lock`"
	break
    fi
    if [ $i -eq 20 ]
    then
	echo "lockpmns: Warning: Unable to acquire lock ($lock)"
	echo "                   after 120 seconds ... continuing anyway"
	exit 1
    fi
    sleep 5
    i=`expr $i + 1`
done

exit 0
