#!/bin/sh
# PCP QA Test No. 036
# Exercise __pmProcessExec() and friends from libpcp.
#
# Copyright (c) 2017 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "=== success cases ==="
src/exectest -Dexec -- /bin/echo 'blah;trickme'
src/exectest -Dexec -- /bin/sh -c "echo 'f o o'; kill -TERM \$\$; sleep 1; echo b\\ a\\ r"

echo
echo "=== error and failure cases ==="
src/exectest -Dexec -- /a/b/c -f oo bar

# success, all done
status=0
exit
