#!/bin/sh
# PCP QA Test No. 036
# Exercise __pmProcessExec() and friends from libpcp.
#
# Copyright (c) 2017 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

# filter pid's in lines like ...
# __pmProcessExec: pid=1965 wait_pid=1965
#
_filter()
{
    tee -a $here/$seq.full \
    | sed \
	-e 's/pid=[0-9][0-9]*/pid=PID/g' \
    #end
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "=== success cases ==="
src/exectest -Dexec -- /bin/echo 'blah;trickme' 2>&1 | _filter
src/exectest -Dexec -- /bin/sh -c "echo 'f o o'; kill -TERM \$\$; sleep 1; echo b\\ a\\ r" 2>&1 | _filter

echo
echo "=== error and failure cases ==="
src/exectest -Dexec -- /a/b/c -f oo bar 2>&1 | _filter

# success, all done
status=0
exit
