#! /bin/sh
# PCP QA Test No. 043
# error encoding in numval within pmResult
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter
. ./common.check

_filter()
{
    sed \
	-e '/pmResult/s/ .* numpmid/ ... numpmid/' \
	-e 's/ value -*[0-9][0-9]*$/ value INTEGER/' \
	-e 's/Permission denied/No permission to perform requested operation/'
}

_cleanup()
{
    _restore_primary_logger
    rm -f $tmp.*
    exit $status
}

status=1
trap "_cleanup" 0 1 2 3 15

# need to make sure the primary pmlogger allows all pmlc access
# from the localhost (by ip addr)
#
admin/allow-pmlc-access >>$seq_full 2>&1

# real QA test starts here
_change_config pmcd on || _exit 1
_change_config pmlogger on || _exit 1
_writable_primary_logger
_service -v pmcd restart >>$seq_full 2>&1 || _exit 1
_wait_for_pmcd || _exit 1
_service -v pmlogger restart >>$seq_full 2>&1 || _exit 1
_wait_for_pmlogger || _exit 1

src/chknumval | _filter
status=0
exit
