#! /bin/sh
# PCP QA Test No. 050
# log operations before the start and after the end
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter
. ./common.check

trap "rm -f $tmp.*; exit" 0 1 2 3 15

# real QA test starts here
for arch in tmparch/foo tmparch/bigbin tmparch/mv-foo tmparch/mv-bigbin tmparch/noti-foo tmparch/noti-bigbin
do
    echo
    echo "Archive $arch ..."
    src/eofarch -a $arch
done
