#!/bin/sh
# PCP QA Test No. 062
# Test pmcd's ability to supress multiple access control warnings from the same
# host
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

rm -f $seq.out
endian=`perl -MConfig -e 'print $Config{byteorder}' | tr -d 5678`
if [ "$endian" = "4321" ]
then
    ln $seq.out.4321 $seq.out
elif [ "$endian" = "1234" ]
then
    ln $seq.out.1234 $seq.out
else
    echo "Arrgh ... cannot determine host endianness"
    exit 1
fi

# real QA test starts here

echo "testing single op for all ops..."
echo "may dump core for IRIX 6.1 ... bug in gethostbyname()"
src/chkacc1
echo

echo "testing all except one op for all ops..."
echo "may dump core for IRIX 6.1 ... bug in gethostbyname()"
src/chkacc2
echo

echo "testing all combinations of ops in a range..."
echo "may dump core for IRIX 6.1 ... bug in gethostbyname()"
src/chkacc3
