#! /bin/sh
# PCP QA Test No. 065
# retrospective stores
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter

trap "rm -f $tmp.*; exit" 0 1 2 3 15

# real QA test starts here
echo "archive past ..."
src/storepast -a tmparch/foo

echo "multi-volume archive past ..."
src/storepast -a tmparch/mv-foo

echo "no index archive past ..."
src/storepast -a tmparch/noti-foo


