#!/bin/sh
# PCP QA Test No. 1019
# Exercise QmcGroup illustrating simple clients and protocols
#
# test really-retired by kenj on 13 Sep 2025
#
# to see the original test
# 	$ git diff 5ce07ea86 -- 1019

seq=`basename $0`
. ./common.product
. ./common.filter
. ./common.check

_notrun 'retired and culled'
