#!/bin/sh
# PCP QA Test No. 1026
# Test for pmdumptext regressions
#
seq=`basename $0`
echo "QA output created by $seq"
. ./common.test

status=0	# success is the default!
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

cd "$PCP_VAR_DIR/testsuite" || \
	_notrun "Cannot find PCP QA testsuite directory"
[ -x ./getpmcdhosts ] || \
	_notrun "Cannot find getpmcdhosts script from PCP QA"
multi=`./getpmcdhosts -p multi -n 1`
[ $? -eq 0 ] || cd $here && _notrun "Cannot get remote multi-CPU machine"
single=`./getpmcdhosts -p single -n 1`
[ $? -eq 0 ] || cd $here && _notrun "Cannot get remote single-CPU machine"
cd $here

_filter()
{
    sed \
    	-e "s/$multi/MULTI/g" \
	-e "s/$single/SINGLE/g" \
	-e 's/[1-2][0-9]*\.000 1\.000/N 1/g' \
	-e 's/[2-9]\.000 1\.000/N 1/g' \
	-e "s/$$/TMP/g"
}

# real QA test starts here

# check support for different hosts at once
eval pmdumptext -lM -s 1 -d "' '" -f "''" $multi:hinv.ncpu $single:hinv.ncpu | _filter

# check that we manage a bad config file OK
pmdumptext -c $tmp.not_here 2>&1 | _filter

# check that instances are converted to canonical units
pmdumptext -C -iu $single:kernel.percpu.cpu.user[cpu0] 2>&1 | _filter

exit
