#!/bin/sh
# PCP QA Test No. 1056
# Check derived metrics help text access returns the
# expected error code.
#
# Copyright (c) 2016 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "cd $here; $sudo rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
echo 'cpus = hinv.ncpu' > $tmp.derived
pminfo --derived $tmp.derived -dtT cpus

# success, all done
status=0
exit
