#!/bin/sh
# PCP QA Test No. 1082
# Exercise python inst string encoding/decoding bug that
# Martins observed and fixed.  See "/tmp/1µsec" instance
# in proc.psinfo.pid sample in archives/procpid-encode &
# also instance #8087 in archives/procpid-encode2.
#
# Copyright (c) 2015 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.check
. ./common.setup
[ -f common.python ] || _notrun "No python bindings installed"

. ./common.python

[ -n "$PCP_PYTHON_PROG" ] || _notrun "no acceptable python to run src/procpid.python"

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "== archives/procpid-encode"
$python $here/src/procpid.python --archive $here/archives/procpid-encode \
	proc.psinfo.pid
echo

echo "== archives/procpid-encode2"
$python $here/src/procpid.python --archive $here/archives/procpid-encode2 \
	proc.psinfo.cpusallowed
echo

# success, all done
status=0
exit
