#!/bin/sh
# PCP QA Test No. 1101
# libpcp_web
#
# Copyright (c) 2017 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_check_valgrind

_filter()
{
    sed \
	-e 's,0x[0-9a-fA-F]*,HEX,g' \
	-e "s,$here,CWD,g" \
    #end
}

status=1	# failure is the default!
trap "cd $here; rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
_run_valgrind src/json_test $here/ceph/ceph_data1.json > $tmp.out 2>&1
cat $tmp.out | tee -a $seq_full | _filter

# success, all done
status=0
exit
