#!/bin/sh
# PCP QA Test No. 1107
# pmie - #'instname' matching tests
#
# See also qa/1142 for live pmcd version.
#
# Copyright (c) 2019 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

_filter()
{
    # DATE is like: Thu Jan 31 08:56:58 2019 or Thu Jan 31 18:20:11
    tee -a $seq.full \
    | sed \
	-e '/.*Info: evaluator exiting/d' \
	-e 's/[A-Z][a-z][a-z] [A-Z][a-z][a-z]  *[0-9][0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9] [0-9][0-9][0-9][0-9]/DATE/' \
	-e 's/[A-Z][a-z][a-z] [A-Z][a-z][a-z]  *[0-9][0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9]/DATE/' \
	-e 's/ pmie([0-9][0-9]*) / pmie(PID) /' \
    # end
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
cat <<'End-of-File' >$tmp.config
some_inst ( proc.psinfo.utime #'INST' > 0) -> print "[%i] %v";
End-of-File

echo "=== proc.psinfo.utime (space in instance name) ==="

for name in "025628 /var/lib/pcp/pmdas/proc/pmdaproc" \
    025628 025628_not_here 02562
do
    echo
    echo "--- $name ---"
    sed -e "s;INST;$name;" <$tmp.config \
    | pmie -z -t 10sec -a archives/20180127.08.40 2>&1 \
    | _filter
done

cat <<'End-of-File' >$tmp.config
some_inst ( disk.dev.total #'INST' > 0) -> print "[%i] %v";
End-of-File

echo
echo "=== disk.dev.total (no space instance name) ==="

for name in "dks54d1 irrelevant disk name" \
    dks54d1 dks54d1_not_here dks54d
do
    echo
    echo "--- $name ---"
    sed -e "s;INST;$name;" <$tmp.config \
    | pmie -z -t 3 -a archives/babylon.pmview_v2 2>&1 \
    | _filter
done

# success, all done
status=0
exit
