#!/bin/sh
# PCP QA Test No. 1120
# pmdaprometheus scalability testing
# specifically scaling amount of turnover between nodes
#
# Copyright (c) 2017 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.prometheus

_pmdaprometheus_check || _notrun "prometheus pmda and/or load generator not installed"

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
totalendpoints=100 #total queue to work through
endpoints=10 #prometheus endpoints
iterations=2
metrics=10
instances=10

_cleanup()
{
    # no need to kill the load generator, it exits itself in this test
    return 0
}

_prepare_pmda prometheus
trap "_cleanup _cleanup_pmda prometheus; exit \$status" 0 1 2 3 15

_pmdaprometheus_save_config
_pmdaprometheus_install

$python $here/prometheus/prometheus_endpoint.python \
	--output=$PCP_PMDAS_DIR/prometheus/urls.d/ \
	--total $totalendpoints \
	--endpoints $endpoints \
	--metrics $metrics \
	--instances $instances \
	--limit $iterations >$tmp.endpoint 2>&1 &
pid=$!

if ! _pmdaprometheus_wait_for_metric prometheus.source2
then
    _pmdaprometheus_restore_config
    status=1
    exit
fi

if pminfo -v prometheus.source0 > $tmp.info 2> $tmp.err
then
    :
else
    echo "... failed! ... here is the Install log ..."
    cat $tmp.out
fi
cat $tmp.info $tmp.err

if pminfo -fd prometheus.source1 > $tmp.info 2>$tmp.err
   then
    echo "Fetch and desc prometheus metrics: success"
    cat $tmp.info
else
    echo "Fetch and desc prometheus metrics: failed"
    cat $tmp.err
fi
for i in `seq 2 1 99`
do
    pminfo -f prometheus.source$i
    sleep 0.5
done

_pmdaprometheus_remove
_pmdaprometheus_restore_config

# success, all done
status=0
exit
