#!/bin/sh
# PCP QA Test No. 1124
# Exercise the BCC PMDA tracepoint hits module - install, remove and values.
#
# Copyright (c) 2018 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.bcc

_pmdabcc_check
_pmdabcc_require_kernel_version 4 7
_pmdabcc_check_tracepoint random:urandom_read

status=1       # failure is the default!
signal=$PCP_BINADM_DIR/pmsignal
$sudo rm -rf $tmp.* $seq.full

_value_filter()
{
    awk '/random:urandom_read/ && /value [1-9][0-9]*/ {print "OK"; exit}'
}

cat <<EOF >$tmp.conf
# Installed by PCP QA test $seq on `date`
[pmda]
modules = tracepoint_hits
prefix = bcc.
[tracepoint_hits]
module = tracepoint_hits
cluster = 100
compile_test = True
tracepoints = random:urandom_read
EOF

_pmdabcc_try_compile $tmp.conf

_prepare_pmda bcc
trap "_pmdabcc_cleanup; exit \$status" 0 1 2 3 15
_stop_auto_restart pmcd

# real QA test starts here
_pmdabcc_install <$tmp.conf
_pmdabcc_wait_for_metric

# Generate system activity for the BCC tracepoint hits module
for i in 0 1 2 3 4 5 6 7 8 9 ; do mktemp -u > /dev/null ; done

echo "=== report metric values ==="
pminfo -dfmtT bcc.tracepoint.hits 2>&1 | tee -a $here/$seq.full \
| _value_filter

_pmdabcc_remove

status=0
exit
