#!/bin/sh
# PCP QA Test No. 1125
# Exercise the BCC PMDA klockstat module - install, remove and values.
#
# Copyright (c) 2019 Red Hat.
#

# test really-retired by kenj on 13 Sep 2025
#
# to see the original test
# 	$ git diff 5da433691 -- 1125

seq=`basename $0`
. ./common.product
. ./common.filter
. ./common.check

_notrun 'retired and culled'
