#!/bin/sh
# PCP QA Test No. 1127
# Exercise the BCC PMDA uprobe hits module - install, remove and values.
#
# Copyright (c) 2018 Red Hat.
#

# test really-retired by nathans on 20 Feb 2026
#
# to see the original test
# 	$ git diff 9a576b8076 -- 1127

seq=`basename $0`
. ./common.product
. ./common.filter
. ./common.check

_notrun 'retired and culled'
