#!/bin/sh
# PCP QA Test No. 1159
# SIGINT for pmlogger, part of
# https://github.com/performancecopilot/pcp/issues/116
#
# See also qa/1109.
#
# Copyright (c) 2017 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
cat <<End-of-File >$tmp.conf
log mandatory on 100 msec {
    containers
    disk
    event
    filesys
    hinv
    ipc
    kernel
    mmv
    pmcd
    pmda
    quota
    rpc
    swap
    swapdev
    sysfs
    tmpfs
    vfs
}
End-of-File

export PCP_DERIVED_CONFIG=
pmlogger -c $tmp.conf -T 5sec -l $tmp.log -m qa/$seq $tmp &
pid=$!

echo "pmlogger PID=$pid" >>$here/$seq.full

$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '[P]ID|[p]mlogger' >>$here/$seq.full

sleep 2
kill -INT $pid
wait

$PCP_PS_PROG $PCP_PS_ALL_FLAGS | egrep '[P]ID|[p]mlogger' >>$here/$seq.full

# Counting is real tricky here ... pmlogger may split the one group in
# the config file into multiple pmFetch's, so just count the number of
# pmda.version records in the archive.
#
# Expected number of records is 2sec / 100msec = 20, but given a possibly
# lame VM, if we see 4 pmResults containing pmda.version, that would be
# good and allow +1 overshoot.
#
if [ -f $tmp.0 ]
then
    cat $tmp.log >>$here/$seq.full
    pmdumplog $tmp pmda.version \
    | tee -a $here/$seq.full \
    | grep 'pmda\.version' \
    | wc -l \
    | $PCP_AWK_PROG '
BEGIN			{ low = 4; high = 21 }
low <= $1 && $1 <= high	{ print "Found " low "-" high " records in archive"; next }
			{ print "Unexpected " $1 " records in archive" }'
else
    echo "Arrgh, pmlogger never got started ..."
    cat $tmp.log
fi

# success, all done
status=0
exit
