#!/bin/sh
# PCP QA Test No. 1221
# test pmda prometheus labels
#
# Note: if anything gets added or changed in qa/prometheus/samples directory,
# then this test (and all tests in group pmda.prometheus) will need to be remade.
#
# Copyright (c) 2017 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.prometheus

_pmdaprometheus_check || _notrun "prometheus pmda and/or load generator not installed"

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full

_filter()
{
    sed \
    -e 's/"userid":[0-9]*/"userid":NUM/' \
    -e 's/"groupid":[0-9]*/"groupid":NUM/' \
    -e 's/"url":"file:.*\.txt"/"url":FILEURL/' \
    -e 's/"hostname":"[a-z0-9][a-z0-9_.-]*"/"hostname":HOSTNAME/'
}

_prepare_pmda prometheus
trap "_cleanup_pmda prometheus >>$here/$seq.full; exit \$status" 0 1 2 3 15

_pmdaprometheus_save_config
_pmdaprometheus_install

# add all the sample text files as urls.
ls -1 $here/prometheus/samples/*.txt | sort | while read file
do
    urlbase=`basename $file .txt | tr .- _`
    echo 'file://'$file > $PCP_PMDAS_DIR/prometheus/urls.d/$urlbase.url
done

if ! _pmdaprometheus_wait_for_metric prometheus.thermostat
then
    _pmdaprometheus_restore_config
    status=1
    exit
fi

if pminfo -l `pminfo prometheus | LC_COLLATE=POSIX sort` 2> $tmp.err | _filter | tee $tmp.info
then
    :
else
    echo "... failed! ... here is the Install log ..."
    cat $tmp.out
fi
cat $tmp.info $tmp.err

_pmdaprometheus_remove
_pmdaprometheus_restore_config

# success, all done
status=0
exit
