#!/bin/sh
# PCP QA Test No. 1240
# Exercise pmrep and fetchgroup handling of counter wrap.
#
# Copyright (c) 2018 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.python

which pmrep >/dev/null 2>&1 || _notrun "No pmrep binary installed"
$python -c "from pcp import pmapi" >/dev/null 2>&1
[ $? -eq 0 ] || _notrun "python pcp pmapi module not installed"

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here

echo
echo "-- raw input archive --"
pmrep -z -w 15 -r -a archives/uwrap sample.wrap.ulong

echo
echo "-- input archive, rate converted --"
pmrep -z -w 15 -a archives/uwrap -t 1sec sample.wrap.ulong

echo
echo "-- input archive, rate converted with PCP_COUNTER_WRAP set --"
PCP_COUNTER_WRAP=on
export PCP_COUNTER_WRAP
pmrep -z -w 15 -a archives/uwrap -t 1sec sample.wrap.ulong

# success, all done
status=0
exit
