#! /bin/sh
# PCP QA Test No. 125
# pv 910632
# __pmLogFetchInterp doing way more reading than it needs to.
#
# Copyright (c) 2002 Silicon Graphics, Inc.  All Rights Reserved.
# 

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=0	# success is the default!
$sudo rm -rf $tmp.*
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
pmval -z -Dlog,interp -O-16 -t 15 -a archives/kenj-pc-1 kernel.all.cpu.idle 2>$tmp.err

echo
echo "__pmLogRead calls: `grep __pmLogRead $tmp.err | wc -l | sed -e 's/ *//g'`"
