QA output created by 1251

=== really_fubar ===
No matching man entry in any section!
--- (1) ---
No match for pattern beyond all recognition

=== pminfo ===
--- (1) ---
No match for pattern fubar

=== pminfo ===
--- (1) ---
OK

=== pmdatxmon ===
--- (1) ---
OK

=== txrecord ===
--- (1) ---
OK

=== genload ===
--- (1) ---
OK

=== KERNEL_PMDAS ===
--- (1) ---
OK

=== PCPIntro ===
--- (1) ---
OK

=== PCPIntro ===
--- (3) ---
OK

=== pmNewContext ===
--- (3) ---
OK

=== pmRecord ===
--- (3) ---
OK

=== pmRecordSetup ===
--- (3) ---
OK

=== pmRecordControl ===
--- (3) ---
OK

=== pcp.env ===
--- (5) ---
OK
