#!/bin/sh
# PCP QA Test No. 1286
# Exercise the BCC PMDA netproc hits module - install, remove and values.
#
# Copyright (c) 2020 Red Hat.
#

# test really-retired by nathans on 20 Feb 2026
#
# to see the original test
# 	$ git diff 9a576b8076 -- 1286

seq=`basename $0`
. ./common.product
. ./common.filter
. ./common.check

_notrun 'retired and culled'
