#!/bin/sh
# PCP QA Test No. 1304
# Exercise pmstat handling of local context fallback.
#
# Copyright (c) 2018 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    _service pmcd restart 2>&1 | _filter_pcp_restart
    _wait_for_pmcd
    _restore_auto_restart pmcd
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
_stop_auto_restart pmcd
if ! _service pmcd stop 2>&1; then _exit 1; fi | _filter_pcp_stop
_wait_pmcd_end || _exit 1

echo "Running pmstat in local context fallback mode"
pmstat --interval 0.2 --samples 3 >$tmp.out 2>$tmp.err
out=`cat $tmp.out`
[ -z "$out" ] || echo "Got pmstat output on stdout"
err=`cat $tmp.err`
[ -z "$err" ] || echo "Got pmstat output on stderr"

# success, all done
status=0
exit
