#!/bin/sh
# PCP QA Test No. 1330
# pmdaopenmetrics scalability testing
# specifically scaling number of metrics per nodes
#
# Copyright (c) 2017 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.openmetrics

_pmdaopenmetrics_check || _notrun "openmetrics pmda and/or load generator not installed"
_have_python266 && _notrun "python load generator does not currently work with python 2.6.6"

status=1	# failure is the default!
totalendpoints=5 #total queue to work through
endpoints=5 #openmetrics endpoints
iterations=5
metrics=400
instances=10

_cleanup()
{
    # load generator exits itself for this test

    echo "=== endpoint log ===" >>$here/$seq.full
    if [ -f $tmp.endpoint ]
    then
	cat $tmp.endpoint >>$here/$seq.full
    else
	echo "Error: endpoint log file is missing" >>$here/$seq.full
    fi

    cd $here
    _pmdaopenmetrics_cleanup
    $sudo rm -rf $tmp $tmp.*
}

_prepare_pmda openmetrics
trap "_cleanup; exit \$status" 0 1 2 3 15
_stop_auto_restart pmcd

_pmdaopenmetrics_save_config
_pmdaopenmetrics_install

port=`_find_free_port 10000`
echo "port=$port" >>$seq_full

$python $here/openmetrics/openmetrics_endpoint.python \
	--port=$port \
	--output=$PCP_PMDAS_DIR/openmetrics/config.d/ \
	--total $totalendpoints \
	--endpoints $endpoints \
	--metrics $metrics \
	--instances $instances \
	--limit $iterations >$tmp.endpoint 2>&1 &
pid=$!

if ! _pmdaopenmetrics_wait_for_metric openmetrics.source4
then
    status=1
    exit
fi

if pminfo -b 1000000 -v `pminfo openmetrics.source0 | LC_COLLATE=POSIX sort` > $tmp.info 2> $tmp.err
then
    :
else
    echo "... failed! ... here is the Install log ..."
    cat $tmp.out
fi
cat $tmp.info $tmp.err

if pminfo -b 1000000 -ftd `pminfo openmetrics.source1 | LC_COLLATE=POSIX sort` > $tmp.info 2>$tmp.err
   then
    echo "Fetch and desc openmetrics metrics: success"
    cat $tmp.info
else
    echo "Fetch and desc openmetrics metrics: failed"
    cat $tmp.err
fi

for i in `seq 0 1 4`
do
    pminfo -b 10000000 -tf `pminfo openmetrics.source$i | LC_COLLATE=POSIX sort`
    pminfo -b 10000000 -tf `pminfo openmetrics.source$i | LC_COLLATE=POSIX sort`
    pminfo -b 10000000 -tf `pminfo openmetrics.source$i | LC_COLLATE=POSIX sort`
    pminfo -b 10000000 -tf `pminfo openmetrics.source$i | LC_COLLATE=POSIX sort`
    sleep 0.5
done
#for i in `seq 2 1 4`
#do
#    pminfo -b 10000000 -tf openmetrics.source$i
#    sleep 0.5
#done

_pmdaopenmetrics_remove

# success, all done
status=0
exit
