#!/bin/sh
# PCP QA Test No. 1401
# Exercise REST API chunked encoding with persistent HTTP
# connections, and end-of-JSON-response EOL strings.
#
# Copyright (c) 2019 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_check_series

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
_service pmproxy stop >/dev/null
_service pmproxy start >>$here/$seq.full 2>&1
_wait_for_pmproxy

# curl maintains a connection when given multiple URLs
echo "Verify no chunk-encoded lengths in output" | tee -a $seq.full
url1='http://localhost:44322/metrics'
curl -s "$url1" "$url1" | tee -a $seq.full > $tmp.out

# remove expected, good comment lines and metric lines
cat $tmp.out \
    | grep -v '^#' \
    | grep -v '} '
echo "Silence is golden"

# curl maintains a connection when given multiple URLs
echo "Verify no unexpected final EOL markers in output" | tee -a $seq.full
url2='http://localhost:44322/pmapi/fetch?names=hinv.ncpu,disk.dev.read'
curl -s "$url2" | tee -a $seq.full > $tmp.out
tail -1 $tmp.out | sed -e 's/{.*}/JSON/g'

# success, all done
status=0
exit
