#!/bin/sh
# PCP QA Test No. 1407
# test pmchart with Iostat view
#
# Copyright (c) 2018 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.qt
status=1	# failure is the default!
trap "_cleanup_qt; exit \$status" 0 1 2 3 15

which pmchart >/dev/null 2>&1 || _notrun "pmchart not installed"
[ -z "$DISPLAY" -a -z "$PCPQA_CLOSE_X_SERVER" ] && _notrun "need DISPLAY or PCPQA_CLOSE_X_SERVER"

$sudo rm -f $tmp.* $seq.full

echo "DISPLAY=$DISPLAY" >>$seq.full
echo "PCPQA_CLOSE_X_SERVER=$PCPQA_CLOSE_X_SERVER" >>$seq.full

_checkerr()
{
    tee <$tmp.err -a $seq.full \
    _filter_qt <$tmp.err >$tmp.tmp
    if [ -s $tmp.tmp ]
    then
	echo "Arrgh ... stderr from pmchart ..."
	cat $tmp.tmp
	exit
    fi
}

# check pmchart can parse Iostat view
#
echo "=== parse Iostat view" | tee -a $seq.full
export PCP_STDERR=$tmp.err
pmchart -C -c Iostat 2>&1 | _filter_qt
[ -s $tmp.err ] && _checkerr

echo "=== expect no output, especially no qt/scaling or divide by zero exceptions" | tee -a $seq.full
pmchart -z -a $here/archives/zero_disk_activity -c Iostat -t 0.1 -O'@fri jul 13 00:11:40' -o $tmp.out.png 2>>$tmp.err
_checkerr

# success, all done
status=0
exit
