#!/bin/sh
# PCP QA Test No. 141
# pmNewContext and archive and fullpathname bug
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter

trap "rm -f $tmp.*; exit" 0 1 2 3 15

# real QA test starts here
echo "=== bar bar ==="
cd src
./badloglabel bar bar

echo
echo "=== bar ./bar ==="
./badloglabel bar ./bar

echo
echo "=== ./bar ./bar ==="
./badloglabel ./bar ./bar

echo
echo "=== bar ...fullpath.../bar ==="
./badloglabel bar `pwd`/bar

echo
echo "=== ...fullpath.../bar ...fullpath.../bar ==="
./badloglabel `pwd`/bar `pwd`/bar
