#!/bin/sh
# PCP QA Test No. 1416
# Exercise log rewrite for Linux uptime and idletime metrics.
#
# Copyright (c) 2020 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

[ $PCP_PLATFORM = linux ] || _notrun "Test only runs on Linux"

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "== Rewriting"
config="$PCP_VAR_DIR/config/pmlogrewrite/linux_kernel_fixups.conf"
pmlogrewrite -c "$config" archives/proc $tmp.proc
echo "status=$?"; echo

echo "== Metadata before"
pminfo -d -a archives/proc kernel.all.uptime kernel.all.idletime
echo

echo "== Metadata after"
pminfo -d -a $tmp.proc kernel.all.uptime kernel.all.idletime
status=0
exit
