#!/bin/sh
# PCP QA Test No. 1466
# test migrate_pid_service rc-proc.sh function
#
# Copyright (c) 2021 Red Hat.  All Rights Reserved.
#
seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

[ "$PCPQA_SYSTEMD" = no ] && _notrun "we're not using systemd here"
[ -n "$PCP_SYSTEMDUNIT_DIR" ] || _notrun "PCP_SYSTEMDUNIT_DIR not set, so no systemd here"
[ -f $PCP_SYSTEMDUNIT_DIR/pmcd.service ] || _notrun "$PCP_SYSTEMDUNIT_DIR/pmcd.service not found"

_cleanup()
{
    cd $here
    # leave pmcd in a known good state
    _service pmcd restart >>$seq.full 2>&1
    _wait_for_pmcd
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
_service pmcd restart 2>&1 >> $seq.full
# in a known clean systemd service state now
_wait_for_pmcd
pmcdpid=`_get_pids_by_name pmcd`

# add a process to the pmcd service cgroup
pmpause >/dev/null 2>&1 &
pid=$!
echo pid=$pid >> $seq.full
echo cgroup=`cat /proc/$pid/cgroup` >> $seq.full
$sudo sh -c ". $PCP_SHARE_DIR/lib/rc-proc.sh; migrate_pid_service -v $pid pmcd.service" 2>&1 >> $seq.full

echo pmsleep >> $seq.full
pmsleep 2
$PCP_PS_PROG $PCP_PS_ALL_FLAGS >> $seq.full
echo new cgroup=`cat /proc/$pid/cgroup` >> $seq.full
echo pmcd cgroup=`cat /proc/$pmcdpid/cgroup` >> $seq.full

if systemctl status pmcd.service 2>&1 | tee $tmp.sts | grep -q -s pmpause
then
    echo PASSED, found pmpause process in pmcd.service cgroup
else
    echo FAILED, did not find pmpause process in pmcd.service cgroup | tee -a $seq.full
    cgroot=`mount | $PCP_AWK_PROG '/^cgroup/ {print $3; exit}'`
    echo cgroot=$cgroot | tee -a $seq.full
    cgslice=`systemctl status pmcd.service | $PCP_AWK_PROG '/CGroup:/ {print $2}'`
    echo cgslice=${cgslice} | tee -a $seq.full
    find ${cgroot} -type d -name pmcd.service -print -exec ls -l {} ";" | tee -a $seq.full
    echo cgroup.procs=${cgslice}/cgroup.procs >> $seq.full
    cat ${cgslice}/cgroup.procs >> $seq.full
    echo systemctl output >> $seq.full
    cat $tmp.sts >> $seq.full
fi

# all done
status=0
exit
