#!/bin/sh
# PCP QA Test No. 1468
# Use libpcp_fault to exercise __pmAllocResult
#
# valgrind variant, see qa/1345 for the non-valgrind variant
#
# check-group-include: pmval fault interp
#
# Copyright (c) 2021 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_check_valgrind

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
export seq
./1345 --valgrind

# success, all done
exit
