#!/bin/sh
# PCP QA Test No. 1517
# derived metric masking tests
#
# valgrind variant, see qa/1513 for the non-valgrind variant
#
# check-group-include: derive
#
# Copyright (c) 2024 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_check_valgrind

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=0	# success is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
export seq
./1513 --valgrind

# success, all done
exit
