#!/bin/sh
# PCP QA Test No. 1538
# PDU hardening - __pmDecodeFetchPDU
#
# Copyright (c) 2024 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

pdu_data=binary/fetch-numpmid
grep_pattern=__pmDecode

# this is one of the generic pmcd PDU exerciser tests ...
#
. ./common.pmcd.pdu

