#!/bin/sh
# PCP QA Test No. 1539
# PDU hardening - __pmDecodeIDList
#
# Copyright (c) 2024 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

pdu_data=pdudata/idlist-numpmid
grep_pattern=__pmDecodeIDList

# this is one of the generic pmcd PDU exerciser tests ...
#
. ./common.pmcd.pdu

