#!/bin/sh
# PCP QA Test No. 1630
# pmlogrewrite - indom redact tests
#
# Copyright (c) 2023 Ken McDonell.  All Rights Reserved.
#

if [ $# -eq 0 ]
then
    seq=`basename $0`
    echo "QA output created by $seq"
else
    # use $seq from caller, unless not set
    [ -n "$seq" ] || seq=`basename $0`
    echo "QA output created by `basename $0` $*"
fi

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check


_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_filter()
{
    $PCP_AWK_PROG '
$1 == "InDom:" && $2 == "2.1" {
	print
	print "..."
	skip=1
	next
    }
skip != 0 && $1 == "InDom:"	{ skip = 0 }
skip != 0 && NF == 0		{ skip = 0 }
skip == 0	{ print }'
}

# real QA test starts here

echo "indom 29.2 { iname redact }" >$tmp.config
pmlogrewrite -v -c $tmp.config tmparch/gap2 $tmp

pmdumplog -im $tmp sample.bin 2>&1 \
| _filter_pmdumplog \
| _filter

# success, all done
exit
