#!/bin/sh
# PCP QA Test No. 1673
# Exercise the BPF PMDA CO-RE bashreadline module - install, remove and values.
#
# Copyright (c) 2022 Sohaib Mohamed.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.bpf

_pmdabpf_check
_pmdabpf_require_kernel_version 5 0
_pmdabpf_require_libbpf_version 0 7
which expect >/dev/null 2>&1 || _notrun "expect binary not installed"

status=1       # failure is the default!
signal=$PCP_BINADM_DIR/pmsignal

cat <<EOF >$tmp.conf
# Installed by PCP QA test $seq on `date`
[bashreadline.so]
enabled=true
EOF
_pmdabpf_tryload $tmp.conf

_non_filter()
{
    grep '"0"' > /dev/null && echo -n 'OK'
}

_cleanup()
{
    cd $here
    _pmdabpf_cleanup
    $sudo rm -rf $tmp $tmp.*
}

_prepare_pmda bpf
trap "_cleanup; exit \$status" 0 1 2 3 15
_stop_auto_restart pmcd

# real QA test starts here
_pmdabpf_install $tmp.conf
_pmdabpf_wait_for_metric

sleep 5

# Generate system activity for the CO-RE execsnoop module
cat <<EOF | expect 1> /dev/null
spawn bash
send "echo this is a test from bash\r"
send "exit\r"
expect eof
EOF

sleep 5

echo "=== report metric values for comm ==="
pminfo -dfmtT bpf.bashreadline.comm 2>&1 | tee -a $seq_full \
| _value_filter_exact '"echo this is a test from bash"'

echo "=== report metric values for pid ==="
pminfo -dfmtT bpf.bashreadline.pid 2>&1 | tee -a $seq_full \
| _value_filter_nonzero

_pmdabpf_remove

status=0
exit
