#!/bin/sh
# PCP QA Test No. 1876
# check pmcd environment, fix for RHBZ1857396
#
# Copyright (c) 2020 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_notrun "retired and culled"
