#!/bin/sh
# PCP QA Test No. 1881
# Exercise pcp-summary(1) reporting of remote loggers.
#
# Copyright (c) 2025 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_cleanup()
{
    cd $here
    $sudo rm -rf $tmp $tmp.*
}

_filter()
{
    sed -e "s,archive: $here,archive: CWD,g"
}

status=0	# success is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# real QA test starts here
pcp -z -a $here/archives/pcp-remotes | _filter

# success, all done
exit
