#!/bin/sh
# PCP QA Test No. 1118
# Exercise the BPF PMDA runqlat module - install, remove and values.
#
# Copyright (c) 2018 Andreas Gerstmayr.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.bpf

_pmdabpf_check
_pmdabpf_require_kernel_version 5 0

status=1       # failure is the default!
signal=$PCP_BINADM_DIR/pmsignal

cat <<EOF >$tmp.conf
# Installed by PCP QA test $seq on `date`
[runqlat.so]
enabled=true
EOF
_pmdabpf_tryload $tmp.conf

_label_filter()
{
    grep '"0-1"' | grep '"statistic":"histogram"' | grep '"lower_bound":0' | grep 'upper_bound":1' > /dev/null && echo 'OK'
}

_prepare_pmda bpf
trap "_pmdabpf_cleanup; exit \$status" 0 1 2 3 15
_stop_auto_restart pmcd

# real QA test starts here
_pmdabpf_install $tmp.conf
_pmdabpf_wait_for_metric

# Generate system activity for the BPF runqlat module
dd if=/dev/urandom bs=`expr 20 \* 1024 \* 1024` count=1 2>/dev/null | bzip2 -9 >> /dev/null

echo "=== report metric values ==="
pminfo -dfmtT bpf.runq.latency 2>&1 | tee -a $here/$seq.full \
| _instances_filter_nonzero

echo "=== check metric labels ==="
pminfo -l bpf.runq.latency 2>&1 | tee -a $here/$seq.full \
| _label_filter

_pmdabpf_remove

status=0
exit
