#! /bin/sh
# PCP QA Test No. 195
# validate new __pmLogOpen() semantics for base archive name deduction
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter

trap "rm -f $tmp.*; exit" 0 1 2 3 15

# real QA test starts here
for arch in src/mv-bigbin src/foo src/null src/mv-bigbin.* src/foo.* src/null.*
do
    echo
    echo "=== $arch ==="
    pmdumplog -l $arch 2>&1 | _filter_pmdumplog
done
