#!/bin/sh
# PCP QA Test No. 1989
# Exercise various pcp-slabinfo(1) command options.
#
# Copyright (c) 2023 Oracle and/or its affiliates.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.python

status=1        # failure is the default!
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

pcp_slabinfo="$PCP_BINADM_DIR/pcp-slabinfo"
test -x $pcp_slabinfo || _notrun "No pcp-slabinfo(1) installed"
pcp_slabinfo="$python $pcp_slabinfo"

# real QA test starts here
echo && echo pcp-slabinfo output : Display default output
PCP_ARCHIVE="archives/pcp-slabinfo" PCP_HOSTZONE=1 $pcp_slabinfo 

archive_first="-a archives/pcp-slabinfo -z -O +1"

echo && echo pcp-slabinfo output : Display output 
pcp $archive_first slabinfo

echo && echo pcp-slabinfo output : Display output when given specified number of samples
pcp $archive_first slabinfo -s 3

status=0
exit
