#!/bin/sh
# PCP QA Test No. 1990
# Exercise various pcp-buddyinfo(1) command options.
#
# Copyright (c) 2023 Oracle and/or its affiliates.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.python

__version=`$python --version 2>&1 | sed -e 's/Python //'`
case "$__version"
in
    2.7.5)	_notrun "Python $__version reports start seconds off-by one for some processes"
    		;;
esac

status=1        # failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

pcp_buddyinfo="$PCP_BINADM_DIR/pcp-buddyinfo"
test -x $pcp_buddyinfo || _notrun "No pcp-buddyinfo(1) installed"
pcp_buddyinfo="$python $pcp_buddyinfo"

# real QA test starts here
echo && echo pcp-buddyinfo output : Display default output
PCP_ARCHIVE="archives/pcp-buddyinfo" PCP_HOSTZONE=1 $pcp_buddyinfo 

archive_first="-a archives/pcp-buddyinfo -z -O +1"

echo && echo pcp-buddyinfo output : Display output 
pcp $archive_first buddyinfo

echo && echo pcp-buddyinfo output : Display output when given specified number of samples
pcp $archive_first buddyinfo -s 3

status=0
exit
