#! /bin/sh
# PCP QA Test No. 209
# pmval dumps core?
#
# Copyright (c) 1995-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard filters
. ./common.product
. ./common.filter

tmp=/tmp/$$
status=0
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
arch=archives/960624.08.17_v2
pmval -z -r -n src/root_irix -U $arch disk.dev.total 2>$tmp.err
cat $tmp.err

# all done
exit
