#! /bin/sh
# PCP QA Test No. 305
# PV 939998 affecting pmgadgets instance cache
#


seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=0	# success is the default!
$sudo rm -rf $tmp.*
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here


src-oss/matchInstanceName "" ""
src-oss/matchInstanceName "" "a"
src-oss/matchInstanceName "" "ab"
src-oss/matchInstanceName "" "ab cd"
src-oss/matchInstanceName "" "ab de"

echo

src-oss/matchInstanceName "a" ""
src-oss/matchInstanceName "a" "a"
src-oss/matchInstanceName "a" "ab"
src-oss/matchInstanceName "a" "ab cd"
src-oss/matchInstanceName "a" "ab de"

echo

src-oss/matchInstanceName "ab" ""
src-oss/matchInstanceName "ab" "a"
src-oss/matchInstanceName "ab" "ab"
src-oss/matchInstanceName "ab" "ab cd"
src-oss/matchInstanceName "ab" "ab de"

echo

src-oss/matchInstanceName "ab cd" ""
src-oss/matchInstanceName "ab cd" "a"
src-oss/matchInstanceName "ab cd" "ab"
src-oss/matchInstanceName "ab cd" "ab cd"
src-oss/matchInstanceName "ab cd" "ab de"

echo 

src-oss/matchInstanceName "ab de" ""
src-oss/matchInstanceName "ab de" "a"
src-oss/matchInstanceName "ab de" "ab"
src-oss/matchInstanceName "ab de" "ab cd"
src-oss/matchInstanceName "ab de" "ab de"

# success, all done
exit
