#!/bin/sh
# PCP QA Test No. 547
# Exercise past security flaws in PCP protocol implementation
#
# Copyright (c) 2013 Red Hat.  All Rights Reserved.
#

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

seq=`basename $0`
echo "QA output created by $seq"

host=localhost
timeout=2
status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
for crash_test in secure/crash-*
do
    echo "$crash_test checking: " | tee -a $seq.full
    python $crash_test $host
    pmcd_wait -t $timeout -h $host
    sts=$?
    echo "$crash_test complete sts=$sts" | tee -a $seq.full
    [ $sts -ne 0 ] && exit
done

# success, all done
status=0
exit
