#! /bin/sh
# PCP QA Test No. 649
# Testing MMV client flags behaviour
#
# Copyright (c) 2010 Aconex.  All Rights Reserved.
#

# get standard filters
. ./common.product
. ./common.filter
. ./common.check

seq=`basename $0`

rm -f $seq.out
if [ $PCP_VER -lt 3600 ]
then
    ln $seq.out.1 $seq.out || exit 1
else
    ln $seq.out.2 $seq.out || exit 1
fi

echo "QA output created by $seq"

status=1
done_clean=false
MMV_STATS_DIR="$PCP_TMP_DIR/mmv"

_cleanup()
{
    if $done_clean
    then
	:
    else
	if [ -f $tmp.pmcd.conf ]
	then
	    $sudo mv $tmp.pmcd.conf $PCP_PMCDCONF_PATH
	fi
	if [ -d $tmp.mmv.dir ]
	then
	    rm -fr "$MMV_STATS_DIR"
	    $sudo mv $tmp.mmv.dir $MMV_STATS_DIR
	fi
	rm -f $tmp.*
	$sudo $PCP_RC_DIR/pcp restart | _filter_pcp_start
	_wait_for_pmcd
	_wait_for_pmlogger
	if $install_on_cleanup
	then
	    ( cd $PCP_PMDAS_DIR/mmv; $sudo ./Install </dev/null >/dev/null 2>&1 )
	else
	    ( cd $PCP_PMDAS_DIR/mmv; $sudo ./Remove </dev/null >/dev/null 2>&1 )
	fi
	done_clean=true
    fi
    exit $status
}

install_on_cleanup=false
pminfo mmv >/dev/null 2>&1 && install_on_cleanup=true

trap "_cleanup" 0 1 2 3 15

_filter()
{
    sed \
	-e '/^mmv.test.interval/d' \
	-e '/^mmv.interval/d' \
    #
}

# real QA starts here
home="$PCP_PMDAS_DIR"
iam=mmv
cd "$home/$iam"
unset ROOT

# copy the pmcd config file to restore state later.
cp $PCP_PMCDCONF_PATH "$tmp.pmcd.conf"
# move the MMV directory to restore contents later.
[ -d $MMV_STATS_DIR ] && $sudo mv -f $MMV_STATS_DIR $tmp.mmv.dir

# start from a known starting point
$sudo ./Remove >/dev/null 2>&1

mkdir "$MMV_STATS_DIR"
chmod 1777 "$MMV_STATS_DIR"

echo
echo "=== $iam agent installation ==="
$sudo ./Install </dev/null >$tmp.out 2>&1
_filter_pmda_install <$tmp.out

$here/src/mmv_genstats

echo
echo "=== Listing with a valid process and with prefix ==="
$here/src/mmv_poke -p $$ -f process "$MMV_STATS_DIR/test"
pmprobe -v mmv | _filter

echo "=== Listing with a valid process and without prefix ==="
$here/src/mmv_poke -p $$ -f noprefix "$MMV_STATS_DIR/test"
pmprobe -v mmv | _filter

echo "=== Listing without a valid process ==="
$here/src/mmv_poke -p 4294967295 -f process "$MMV_STATS_DIR/test"
pmprobe -v mmv | _filter

echo
echo "=== remove $iam agent ==="
$sudo ./Remove >$tmp.out 2>&1
_filter_pmda_remove <$tmp.out

echo
echo "=== $iam agent re-installation ==="
cat <<End-of-File | $sudo ./Install >$tmp.out 2>&1
b
dso
End-of-File
_filter_pmda_install <$tmp.out

status=0
exit
