#! /bin/sh
# PCP QA Test No. 654
# checks basic pmdagfs2 functionality
# Requires GFS2 support in the kernel, else it will notrun.
#
# Copyright (c) 2013 Red Hat, Inc.  All Rights Reserved.
#
seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check
. ./common.gfs2

# Attempt to set up the gfs2 pmda test enviroment
_gfs2_filesystem_support_tests

# check for any loopback devices, cowardly abort this test if any exist
loopcount=`$sudo losetup -a | wc -l`
[ $loopcount -eq 0 ] || _notrun "System has loop devices already, bailing"

iam=gfs2
status=1	# failure is the default!
trap "_cleanup" 0 1 2 3 15

$sudo rm -fr $tmp.*.dir
$sudo rm -f $tmp.* $seq.full
touch $here/$seq.full

# real QA test starts here
_prepare_pmda_install $iam
_install_pmda
_setup_gfs2_mounts

echo 
echo "=== Check for successful install of pmda ==" | tee -a $here/$seq.full
pminfo -v gfs2 > /dev/null || _fail "install failed?"

echo
echo "=== Check that the number of metrics are correct ===" | tee -a $here/$seq.full
[ `_pmcount gfs2` -ge 105 ] || _fail "Too few metrics?"

echo
echo "=== Basic glock stats from all kernels ===" | tee -a $here/$seq.full
pminfo -fdm gfs2.glocks | _filter_pminfo

echo
echo "=== Additional glstats for all filesystems ===" | tee -a $here/$seq.full
pminfo -fdm gfs2.glstats | _filter_pminfo

echo
echo "=== Additional sbstats for all filesystems ===" | tee -a $here/$seq.full
pminfo -fdm gfs2.sbstats | _filter_pminfo

echo
echo "=== Removing the GFS2 PMDA ===" | tee -a $here/$seq.full
_remove_pmda

status=0
exit
