#! /bin/sh
# PCP QA Test No. 660
# checks basic pmwebd functionality
#
# Copyright (c) 2013 Red Hat, Inc.  All Rights Reserved.
#
seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check
. ./localconfig

# 3702
[ $PCP_VER -gt 3700 ] || _notrun "Installed pcp is too old"

if which wget >/dev/null 2>&1
then
    echo Found wget
else
    _notrun no wget
fi

if python 660.py --version 2>/dev/null
then
    echo python ok
else
    _notrun python/modules missing 
fi


_cleanup()
{
    rm -fr $tmp.dir
    rm -f $tmp.*
    kill $pid 2>/dev/null
    exit $status
}

_filter()
{
    sed -e 's,#[0-9]*,####,g'
}


iam=pmwebd
status=1	# failure is the default!
trap "_cleanup" 0 1 2 3 15

rm -fr $tmp.dir
rm -f $tmp.*

unset http_proxy
unset HTTP_PROXY

echo
echo "=== 1. pmwebd default startup  ==="
pmwebd 2>$tmp.out &
pid=$!
sleep 2
if grep -q IPv4 $tmp.out; then
    wget -q -O - 'http://localhost:44323/pmapi/context?local=ANYTHING' | awk '{print $2}'
fi
if grep -q IPv6 $tmp.out; then
    wget -q -O - 'http://localhost6:44323/pmapi/context?local=ANYTHING'  | awk '{print $2}'
fi

echo
echo "=== 2. pmwebd exercise via python ==="
if grep -q IPv4 $tmp.out; then
  python 660.py --host localhost | _filter
fi
if grep -q IPv6 $tmp.out; then
  python 660.py --host localhost6 | _filter
fi

status=0
sleep 2
exit
