#!/bin/sh
# PCP QA Test No. 707
# Exercise python PMAPI layer - basic archive tests
#
# Copyright (c) 2012-2014 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.python
status=1	# failure is the default!
$sudo rm -f $tmp.* $seq.full
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

$python -c 'from pcp import pmapi' 2>/dev/null
test $? -eq 0 || _notrun 'Python pcp pmapi module is not installed'

# real QA test starts here
$python $here/src/test_pcp.py src/pyapi.0 >$seq.full 2>&1
_check_unittest archive $seq.full
status=$?
exit
