#!/bin/sh
# PCP QA Test No. 719
# Exercise the pmParseHostSpec API family

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

_check_valgrind
[ $PCP_VER -ge 3800 ] || _notrun "Installed libpcp lacks host parse APIs"

status=0	# success is the default!
$sudo rm -rf $tmp.* $seq.full
trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15

_run_valgrind src/parsehostspec nas1.servers.com:44321,4321@firewall.servers.com:44322
_run_valgrind src/parsehostspec nas1.servers.com:44321@firewall.servers.com:44322
_run_valgrind src/parsehostspec nas1.servers.com:44321@firewall.servers.com
_run_valgrind src/parsehostspec nas1.servers.com@firewall.servers.com
_run_valgrind src/parsehostspec nas1.servers.com:44321
