#!/bin/sh
# PCP QA Test No. 744
# Exercise the NVIDIA GPU PMDA, basic fetch testing.
#
# Copyright (c) 2014-2015 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

[ -f $PCP_PMDAS_DIR/nvidia/pmdanvidia ] || _notrun "nvidia pmda not installed"

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

test -f $here/src/libnvidia-ml.$DSO_SUFFIX || \
	_notrun "No NVIDIA QA wrapper library is available"
for dir in $PCP_LIB_DIR $PCP_LIB32_DIR
do
    if [ -d $dir ]
    then
	$sudo find $dir -name libnvidia-ml.$DSO_SUFFIX >$tmp.libs
	if [ -s $tmp.libs ]
	then
	    _notrun "Conflicting system NVIDIA library found: `cat $tmp.libs`"
	    # NOTREACHED
	fi
    fi
done

_filter()
{
    sed -e 's/.* pminfo\(.*\) Info:/pminfo[PID] Info:/g'
}

pmns=$PCP_PMDAS_DIR/nvidia/root
pmda=$PCP_PMDAS_DIR/nvidia/pmda_nvidia,nvidia_init
_make_helptext nvidia

# real QA test starts here
echo
echo "== Testing behaviour with no nvidia library available"
pminfo -L -K clear -K add,120,$pmda -dfmtT -n $pmns nvidia 2>&1 | _filter

echo
echo "== Testing behaviour with QA wrapper nvidia library"
export LD_LIBRARY_PATH=$here/src
pminfo -L -K clear -K add,120,$pmda -dfmtT -n $pmns nvidia 2>&1 | _filter

# success, all done
status=0
exit
