#!/bin/sh
# PCP QA Test No. 848
# Ensure local connections still work if -Q is specified
#
# Copyright (c) 2016 Martins Innus.  All Rights Reserved.
#

# test really-retired by kenj on 08 Aug 2026
#
# to see the original test
# 	$ git diff 8bcc1345ab -- 848

seq=`basename $0`
. ./common.product
. ./common.filter
. ./common.check

_notrun 'retired and culled'
