#!/bin/sh
# PCP QA Test No. 851
#
# Tests various pcp-iostat features.
#
# Second part of 1099 that is conditional on availability of the
# metrics disk.dev.avactive, disk.dev.read_merge, et al. in the
# platform PMDA.
#
# Copyright (c) 2016 Ken McDonell.  All Rights Reserved.
# Copyright (c) 2016 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

which pmiostat >/dev/null 2>&1 || _notrun "pmiostat binary not installed"

for metric in disk.dev.avactive disk.dev.read_rawactive \
    disk.dev.read_merge disk.dev.write_rawactive disk.dev.write_merge
do
    numval=`pmprobe $metric | $PCP_AWK_PROG '{ print $2 }'`
    case "$numval"
    in
	[0-9]*)
	    ;;
	*)
	    _notrun "metric $metric not available for pcp-iostat"
	    ;;
    esac
done

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "cd $here; rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here

echo '== testing pmiostat --samples option samples sufficiently (2,3)'
pmiostat -t 0.01 -s 1 | wc -l
pmiostat -t 0.01 --samples 2 | wc -l

# success, all done
status=0

exit
