#!/bin/sh
# PCP QA Test No. 884
# libpcp_web qa
#
# Copyright (c) 2016 Red Hat.  All Rights Reserved.

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
trap "cd $here; rm -rf $tmp $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
src/json_test "$here/ceph/ceph_data1.json"

# success, all done
status=0
exit
