#!/bin/sh
# PCP QA Test No. 904
# More detailed exercising of python namespace traversal.
#
# Copyright (c) 2015 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.python

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

$python -c "from pcp import pmapi" >/dev/null 2>&1
[ $? -eq 0 ] || _notrun "python pcp pmapi module not installed"

_filter()
{
    sed -e \
	's/Ran [0-9][0-9]* test.*/TEST TIMING/g' \
    #end
}

# real QA test starts here
$python $here/src/test_pmnswalk.python 2>$tmp.err
echo
echo -- stderr --
cat $tmp.err | _filter 
echo -- ====== --

# success, all done
status=0
exit
