#!/bin/sh
# PCP QA Test No. 918
# Check pmcd with systemd - autorestart
#
# Copyright (c) 2017 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

[ "$PCPQA_SYSTEMD" = no ] && _notrun "we're not using systemd here"
[ -n "$PCP_SYSTEMDUNIT_DIR" ] || _notrun "PCP_SYSTEMDUNIT_DIR not set, so no systemd here"
[ -f $PCP_SYSTEMDUNIT_DIR/pmcd.service ] || _notrun "$PCP_SYSTEMDUNIT_DIR/pmcd.service not found"
grep '^Restart=always' $PCP_SYSTEMDUNIT_DIR/pmcd.service >/dev/null || _notrun "no Restart=always in $PCP_SYSTEMDUNIT_DIR/pmcd.service"

_cleanup()
{
    cd $here
    _service pmcd stop >>$seq_full 2>&1
    _service pmcd restart 2>&1 | _filter_pcp_restart
    _wait_for_pmcd
    _service pmlogger restart 2>&1 | _filter_pcp_restart
    _wait_for_pmlogger
    $sudo rm -rf $tmp $tmp.*
}

status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

# get to a known starting point as far as systemd is concerned
#
if ! _service -v pmcd restart >$tmp.tmp 2>&1; then cat $tmp.tmp; exit; fi
cat $tmp.tmp >>$seq_full
_wait_for_pmcd || exit

# real QA test starts here
old_pid=`_get_pids_by_name pmcd`
$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mcd( |$)' >>$seq_full
echo "old_pid=$old_pid" >>$seq_full

echo "expect success ..."
pmprobe hinv.ncpu

$sudo $PCP_BINADM_DIR/pmsignal -a -s TERM pmcd
_wait_for_pmcd || exit

new_pid=`_get_pids_by_name pmcd`
$PCP_PS_PROG $PCP_PS_ALL_FLAGS | grep -E '[P]PID|/[p]mcd( |$)' >>$seq_full
echo "new_pid=$new_pid" >>$seq_full

if [ "$new_pid" != "$old_pid" ]
then
    echo "pmcd's PID changed, yippee"
else
    echo "Error: pmcd's PID ($old_pid) did not change, see $seq.full"
fi

echo "expect success ..."
pmprobe hinv.ncpu

# This test has 3 (re)starts, so we need it to run for (at least)
# 6 seconds to avoid hitting the systemd StartLimit* limits
#
sleep 6

# success, all done
status=0
exit
