#!/bin/sh
# PCP QA Test No. 919
# Check pmlogger config for pmstat
#
# Copyright (c) 2014 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

rm -f $seq.out
case $PCP_PLATFORM
in
    darwin)
	ln $seq.out.darwin $seq.out || exit 1
	;;
    *)
	ln $seq.out.default $seq.out || exit 1
	;;
esac

_filter()
{
    sed \
	-e '/^@/s/.*/@ DATE/' \
	-e 's/ *?/ ?/g' \
	-e 's/ *[0-9][0-9.]*[mgKM]*/ N/g'
}

# real QA test starts here

# 5 samples @ 0.55 sec should be enough to get 2 results @ 1 sec from
# pmstat
#
pmlogger -c $PCP_VAR_DIR/config/pmlogger/config.pmstat -t 0.55 -s 5 -l $tmp.log $tmp
cat $tmp.log >>$seq.full
pmdumplog -dilmst $tmp >>$seq.full

pmstat -t 1 -a $tmp | tee -a $seq.full | _filter

# success, all done
status=0

exit
