#!/bin/sh
# PCP QA Test No. 962
# Check interp mode in the presence of <mark> records for different
# sample intervals.
#
# Copyright (c) 2014 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
echo "<mark> records ..."
pmdumplog -z -x archives/count-mark | grep '^[^ ]' >$tmp.out
for line in `$PCP_AWK_PROG <$tmp.out '/\<mark\>/ { print NR }'`
do
    a=`expr $line - 2`
    b=`expr $line + 2`
    sed -n -e "${a},${b}p" <$tmp.out
done
echo

for delta in 1min 15min 1hr 4hr 12hr
do
    pmval -a archives/count-mark -z -A $delta -t $delta kernel.all.pswitch
done

# success, all done
status=0

exit
