#!/bin/sh
# PCP QA Test No. 980
# Basic archive mode validation of the Python pmcc module
# (pmcc -> Performance Metrics Convenience Classes)
#
# Copyright (c) 2014 Red Hat.
#

seq=`basename $0`
echo "QA output created by $seq"

. ./common.python
status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

$python -c 'from pcp import pmcc' 2>/dev/null
test $? -eq 0 || _notrun 'Python pcp pmcc module is not installed'

# real QA test starts here
$python $here/src/test_pmcc.py -a src/pmatop-log.0 >$seq.full 2>&1
_check_unittest archive $seq.full
status=$?
exit
