#!/bin/sh
# PCP QA Test No. 984
# Exercise units translation for cgroups metrics.
#
# Copyright (c) 2015 Red Hat.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# cull line like this ...
# --- /tmp/984-25969.1	2015-01-22 19:32:20.554644508 +1100
# +++ /tmp/984-25969.2	2015-01-22 19:32:20.559693083 +1100
_filter()
{
    sed \
	-e '/^---/d' \
	-e '/^+++/d'
}

config=$PCP_VAR_DIR/config/pmlogrewrite/cgroup_units.conf
log_in=$here/archives/cgroups-units
log_out=$tmp.cgroups

# real QA test starts here
echo Rewriting damaged archive
pmlogrewrite -c $config $log_in $log_out

echo Comparing before to after
pminfo --desc --archive $log_in > $tmp.1
pminfo --desc --archive $log_out > $tmp.2
diff -u $tmp.1 $tmp.2 \
| _filter

echo Verify cgroup metrics help
pminfo -Tt cgroup | grep 'help text is not available'

# success, all done
status=0
exit
