#!/bin/sh
# PCP QA Test No. 998
# Exercise libpcp: unlock context before returning
# See https://github.com/performancecopilot/pcp/pull/50
#
# Copyright (c) 2015 Ken McDonell.  All Rights Reserved.
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

status=1	# failure is the default!
$sudo rm -rf $tmp $tmp.* $seq.full
trap "cd $here; $sudo rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# Expect this ...
# Unlock Fail: Operation not permitted
# may see this on Solaris/OpenIndiana ...
# Unlock Fail: Not owner
#
_filter()
{
    sed \
	-e '/Unlock Fail/s/Not owner/Operation not permitted/' \
    # end
}

# real QA test starts here
echo "=== -x (no context) ==="
src/github-50 -x 2>&1 | _filter

echo
echo "=== no args, default context ==="
src/github-50 2>&1 | _filter

echo
echo "=== -h local: ==="
src/github-50 -h 'local:' 2>&1 | _filter

echo
echo '=== -h `hostname` ==='
src/github-50 -h `hostname` 2>&1 | _filter

echo
echo '=== -L ==='
$sudo_local_ctx src/github-50 -L 2>&1 | _filter

echo
echo '=== -a archives/ok-foo ==='
src/github-50 -a archives/ok-foo 2>&1 | _filter

# success, all done
status=0

exit
