#! /bin/sh
#
# Copyright (c) 2026 Red Hat.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# Install the IBM Db2 PMDA
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=db2
domain=42
python_opt=true
daemon_opt=false

conf=$PCP_SYSCONF_DIR/$iam/db2.conf
if [ ! -f "$conf" ]; then
    echo "Error: missing config file \"$conf\""
    status=1
    exit
fi

$PCP_PYTHON_PROG -c "import ibm_db" >/dev/null 2>&1
if test $? -ne 0; then
    echo "Python 'ibm_db' module is not installed"
    status=1
    exit
fi

pmdaSetup
pmdaInstall
exit
